/* eslint-disable max-len, perfectionist/sort-imports, perfectionist/sort-objects */
// @ts-nocheck
import { getSimulationRoster } from '@/domains/tactical/simulationRosters';
import { TutorialIds } from '@/domains/tutorial/tutorialIds';
import { RouteNames } from '@/navigation/routeNames';

export const GuidanceProgramIds = Object.freeze({
  coach: 'coach',
  leagueIntro: 'league_intro',
  player: 'player',
  president: 'president',
});

const tutorialTarget = (tutorialId, routeName, params = undefined) => ({
  params,
  routeName,
  tutorialId,
});

// Contrat (tous optionnels et retro-compatibles) des champs d'abonnement d'une mission :
// - audience.requiresAccessLevel : contrainte de VISIBILITE. Valeur string ou string[] parmi
//   'FREE' | 'TEAM' | 'CLUB_UNVERIFIED' | 'CLUB'. La mission n'est visible que si le
//   subscriptionAccessLevel courant du contexte est inclus. Champ absent = aucune contrainte
//   d'abonnement (comportement historique strictement inchange). Ex : requiresAccessLevel: 'FREE'
//   rend la mission visible seulement pour un compte encore gratuit, masquee des qu'il passe TEAM/CLUB.
// - premiumFeature : METADONNEE pure (booleen) lue par l'UI. N'affecte PAS la visibilite. L'UI affiche
//   un badge Premium sur la mission si premiumFeature === true ET que le contexte n'est pas deja couvert
//   (context.hasActiveEntitlement === false).
// Contexte d'audience expose par buildGuidanceAudienceContext (guidanceEngine.js) pour l'UI et le moteur :
// subscriptionAccessLevel, hasActiveEntitlement, entitlementsSummary, freeUsageSummary.
const mission = (definition) => definition;

const planningTarget = tutorialTarget(TutorialIds.PLANNING, RouteNames.HomeTab, {
  screen: RouteNames.MyEventList,
});
const profileTarget = tutorialTarget(TutorialIds.PROFILE_MAIN, RouteNames.ProfileStack, {
  screen: RouteNames.Profile,
});
const profileEditTarget = tutorialTarget(TutorialIds.PROFILE_EDIT, RouteNames.ProfileStack, {
  screen: RouteNames.ProfileEdit,
});
const messagingTarget = tutorialTarget(TutorialIds.MESSAGING, RouteNames.HomeTab, {
  screen: RouteNames.Chat,
});
const teamHubTarget = {
  params: { screen: RouteNames.MyTeamList },
  routeName: RouteNames.HomeTab,
};
const searchHubTarget = (tutorialId, activeType, params = undefined) => tutorialTarget(
  tutorialId,
  RouteNames.SearchHub,
  {
    activeType,
    ...(params || {}),
  },
);
const searchEventsTarget = searchHubTarget(TutorialIds.SEARCH_EVENTS, 'events');
const searchClubsTarget = searchHubTarget(TutorialIds.SEARCH_CLUBS, 'clubs');
const searchRecruitmentTarget = searchHubTarget(TutorialIds.SEARCH_RECRUITMENT, 'recruitment');
const searchReservationsTarget = searchHubTarget(TutorialIds.SEARCH_RESERVATIONS, 'reservations');
const requestsTarget = tutorialTarget(TutorialIds.REQUESTS_DASHBOARD, RouteNames.RequestsHub, {
  initialFilter: 'all',
  source: 'guidance',
});
const leagueDashboardTarget = {
  params: { screen: RouteNames.LeagueDashboard },
  routeName: RouteNames.LeagueHomeTab,
};

// --- Cibles du tour guide coach (declenche en fin d'onboarding) ---
// Etape creation : ouvre le vrai wizard evenement depuis l'EventStack, avec le spotlight dedie.
const eventWizardTarget = tutorialTarget(TutorialIds.EVENT_WIZARD_TYPE, RouteNames.EventStack, {
  screen: RouteNames.EventWizardType,
});
// Etape composition : board en MODE SIMULATION (aucune ecriture serveur). Le roster fictif est
// derive du sport de l'equipe entrainee (sinon sport prefere du profil, sinon football) pour que
// terrain ET postes collent au sport reel du coach; simulationMode:true active le sandbox.
const resolveCoachSimulationSport = (context) => {
  const userData = context?.userData;
  const trainedTeamSport = (Array.isArray(userData?.trainedTeams) ? userData.trainedTeams : [])
    .flatMap((team) => (Array.isArray(team?.activities) ? team.activities : []))
    .map((activity) => activity?.name)
    .find(Boolean);
  return trainedTeamSport || userData?.preferredSport || 'football';
};
const compositionSimulationTarget = {
  params: (context) => {
    const simulationSport = resolveCoachSimulationSport(context);
    return {
      params: {
        canEdit: true,
        editorMode: 'event',
        players: getSimulationRoster(simulationSport),
        simulationMode: true,
        sport: simulationSport,
        teamName: 'Equipe demo',
      },
      screen: RouteNames.TacticalBoardV2,
    };
  },
  routeName: RouteNames.EventStack,
};
// Etape finale du tour : ecran recap des offres (Gratuit / Equipe / Club avec prix),
// le seul moment de vente. Enregistre dans PrivateNavigator (route GuideOffersRecap).
const offersRecapTarget = {
  routeName: RouteNames.GuideOffersRecap,
};

export const guidanceCatalog = Object.freeze({
  packs: [
    {
      id: 'player_foundations',
      order: 1,
      phase: 'Fondations',
      programId: GuidanceProgramIds.player,
      teaser: 'Les gestes de base pour prendre FoundClub en main.',
      title: 'Premiers repères',
    },
    {
      id: 'player_search',
      order: 2,
      phase: 'Usages coeur',
      programId: GuidanceProgramIds.player,
      teaser: 'Découvrir toutes les surfaces de recherche et de découverte.',
      title: 'Explorer et trouver',
    },
    {
      id: 'player_actions',
      order: 3,
      phase: 'Outils avancés',
      programId: GuidanceProgramIds.player,
      teaser: 'Transformer la découverte en vraies actions de joueur.',
      title: 'Passer à l’action',
    },
    {
      id: 'coach_foundations',
      order: 1,
      phase: 'Fondations',
      programId: GuidanceProgramIds.coach,
      teaser: 'Retrouver rapidement les espaces quotidiens d’un entraîneur.',
      title: 'Base coach',
    },
    {
      id: 'coach_operations',
      order: 2,
      phase: 'Usages coeur',
      programId: GuidanceProgramIds.coach,
      teaser: 'Piloter planning, effectifs et demandes sans quitter l’app.',
      title: 'Pilotage terrain',
    },
    {
      id: 'coach_recruitment',
      order: 3,
      phase: 'Outils avancés',
      programId: GuidanceProgramIds.coach,
      teaser: 'Aller jusqu’au recrutement, aux filtres avancés et aux alertes.',
      title: 'Recrutement et suivi',
    },
    {
      id: 'coach_tour',
      order: 4,
      phase: 'Tour guide',
      programId: GuidanceProgramIds.coach,
      teaser: 'Rejouer pas a pas le tour guide de decouverte lance en fin d onboarding.',
      title: 'Tour guide coach',
    },
    {
      id: 'president_foundations',
      order: 1,
      phase: 'Fondations',
      programId: GuidanceProgramIds.president,
      teaser: 'Poser les bases de navigation d’un dirigeant sur FoundClub.',
      title: 'Base dirigeant',
    },
    {
      id: 'president_operations',
      order: 2,
      phase: 'Usages coeur',
      programId: GuidanceProgramIds.president,
      teaser: 'Piloter club, planning, équipes et événements depuis les bons hubs.',
      title: 'Pilotage club',
    },
    {
      id: 'president_requests_recruitment',
      order: 3,
      phase: 'Usages coeur',
      programId: GuidanceProgramIds.president,
      teaser: 'Maîtriser les flux de demandes, validation et recrutement.',
      title: 'Demandes et recrutement',
    },
    {
      id: 'president_finance_structure',
      order: 4,
      phase: 'Outils avancés',
      programId: GuidanceProgramIds.president,
      teaser: 'Explorer les outils de structure, cotisations, installations et réservations.',
      title: 'Structure et finances',
    },
    {
      id: 'president_advanced',
      order: 5,
      phase: 'Outils avancés',
      programId: GuidanceProgramIds.president,
      teaser: 'Aller jusqu’aux surfaces avancées, aide, League et supervision quotidienne.',
      title: 'Maitrise dirigeant',
    },
    {
      id: 'league_intro',
      order: 1,
      phase: 'Découverte League',
      programId: GuidanceProgramIds.leagueIntro,
      teaser: 'Comprendre les surfaces clés de FoundClub League.',
      title: 'Découvrir League',
    },
  ],
  programs: [
    {
      description: 'Découvrir les outils joueur de la recherche jusqu’à la participation.',
      id: GuidanceProgramIds.player,
      title: 'Progression Joueur',
    },
    {
      description: 'Prendre en main les outils entraîneur au quotidien.',
      id: GuidanceProgramIds.coach,
      title: 'Progression Entraîneur',
    },
    {
      description: 'Explorer en profondeur les surfaces de pilotage dirigeant.',
      id: GuidanceProgramIds.president,
      title: 'Progression Dirigeant',
    },
    {
      description: 'Faire un tour guidé des outils League utiles au rôle courant.',
      id: GuidanceProgramIds.leagueIntro,
      title: 'Découverte League',
    },
  ],
  version: 1,
  missions: [
    mission({
      actionsToTry: ['Vérifier vos informations personnelles', 'Ouvrir la modification de profil'],
      audience: { roleKeys: ['player'] },
      completionMode: 'auto',
      completionSignal: { key: 'profileBasicsComplete', type: 'state' },
      id: 'player_profile_basics',
      longDescription: 'Commencez par vérifier votre profil joueur. C’est le point de départ de la plupart des expériences FoundClub: recherche, invitations, repères d’équipe et suivi personnel.',
      module: 'profile',
      navTarget: profileEditTarget,
      packId: 'player_foundations',
      prerequisiteMissionIds: [],
      priority: 10,
      programId: GuidanceProgramIds.player,
      rewardText: 'Un profil lisible rend vos prochaines missions beaucoup plus fluides.',
      shortDescription: 'Vérifiez ou complétez votre profil joueur.',
      title: 'Compléter mon profil',
      tutorialTarget: profileEditTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir le planning', 'Repérer le résumé personnel en haut de l’écran'],
      audience: { roleKeys: ['player'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.MyEventList, type: 'route' },
      id: 'player_open_planning',
      longDescription: 'Le planning concentre vos événements à venir, vos actions de présence et vos repères quotidiens. C’est un hub fondamental pour un joueur.',
      module: 'planning',
      navTarget: planningTarget,
      packId: 'player_foundations',
      prerequisiteMissionIds: ['player_profile_basics'],
      priority: 20,
      programId: GuidanceProgramIds.player,
      rewardText: 'Vous saurez toujours où retrouver vos rendez-vous sportifs.',
      shortDescription: 'Ouvrez votre planning FoundClub.',
      title: 'Aller dans mon planning',
      tutorialTarget: planningTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir l’onglet équipe', 'Repérer les équipes auxquelles vous appartenez'],
      audience: { requiresTeamAffiliation: true, roleKeys: ['player'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.MyTeamList, type: 'route' },
      id: 'player_open_team_space',
      longDescription: 'Votre espace équipe vous montre vos collectifs, leurs détails et les accès rapides liés à votre pratique.',
      module: 'team',
      navTarget: teamHubTarget,
      packId: 'player_foundations',
      prerequisiteMissionIds: ['player_open_planning'],
      priority: 30,
      programId: GuidanceProgramIds.player,
      rewardText: 'Vous saurez où retrouver votre collectif et ses informations clés.',
      shortDescription: 'Retrouvez votre espace équipe.',
      title: 'Ouvrir mon espace équipe',
    }),
    mission({
      actionsToTry: ['Ouvrir la messagerie', 'Observer les conversations disponibles'],
      audience: { roleKeys: ['player'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.Chat, type: 'route' },
      id: 'player_open_messages',
      longDescription: 'La messagerie vous permet de suivre les échanges du club, des équipes et des conversations directes sans sortir de FoundClub.',
      module: 'messaging',
      navTarget: messagingTarget,
      packId: 'player_foundations',
      prerequisiteMissionIds: ['player_open_team_space'],
      priority: 40,
      programId: GuidanceProgramIds.player,
      rewardText: 'Vous repérez le hub de communication à utiliser au quotidien.',
      shortDescription: 'Ouvrez la messagerie FoundClub.',
      title: 'Explorer la messagerie',
      tutorialTarget: messagingTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir Rechercher', 'Basculer sur les événements'],
      audience: { roleKeys: ['player'] },
      completionMode: 'auto',
      completionSignal: { key: 'search.tab.events', type: 'interaction' },
      id: 'player_search_events',
      longDescription: 'La recherche événements est le point d’entrée naturel pour découvrir entraînements, matchs ouverts, détections et opportunités proches de vous.',
      module: 'search',
      navTarget: searchEventsTarget,
      packId: 'player_search',
      prerequisiteMissionIds: ['player_open_messages'],
      priority: 50,
      programId: GuidanceProgramIds.player,
      rewardText: 'Vous savez où trouver des événements à rejoindre.',
      shortDescription: 'Ouvrez la recherche d’événements.',
      title: 'Rechercher un événement',
      tutorialTarget: searchEventsTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir les filtres événement', 'Repérer comment affiner une recherche'],
      audience: { roleKeys: ['player'] },
      completionMode: 'manual_fallback',
      completionSignal: { routeName: RouteNames.EventFilters, type: 'route' },
      id: 'player_event_filters',
      longDescription: 'Les filtres événement permettent de cibler une activité, une période, une équipe, un club ou une nature d’événement. Même sans tout utiliser, les connaître change la découverte.',
      module: 'search',
      navTarget: { routeName: RouteNames.EventFilters },
      packId: 'player_search',
      prerequisiteMissionIds: ['player_search_events'],
      priority: 60,
      programId: GuidanceProgramIds.player,
      rewardText: 'Vous pourrez aller plus vite vers les événements vraiment pertinents.',
      shortDescription: 'Découvrez les filtres événement.',
      title: 'Explorer les filtres événement',
    }),
    mission({
      actionsToTry: ['Basculer vers les clubs', 'Observer les résultats et fiches club'],
      audience: { roleKeys: ['player'] },
      completionMode: 'auto',
      completionSignal: { key: 'search.tab.clubs', type: 'interaction' },
      id: 'player_search_clubs',
      longDescription: 'La recherche clubs aide à découvrir l’écosystème autour de vous: structures, identités visuelles, contexte et points d’entrée utiles.',
      module: 'search',
      navTarget: searchClubsTarget,
      packId: 'player_search',
      prerequisiteMissionIds: ['player_event_filters'],
      priority: 70,
      programId: GuidanceProgramIds.player,
      rewardText: 'Vous savez aussi explorer les structures, pas seulement les événements.',
      shortDescription: 'Ouvrez la recherche de clubs.',
      title: 'Découvrir les clubs',
      tutorialTarget: searchClubsTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir les annonces recrutement', 'Repérer les profils recherchés'],
      audience: { roleKeys: ['player'] },
      completionMode: 'auto',
      completionSignal: { key: 'search.tab.recruitment', type: 'interaction' },
      id: 'player_search_recruitment',
      longDescription: 'Les annonces de recrutement et détections complètent la recherche classique. Elles montrent les besoins explicites des équipes et clubs.',
      module: 'recruitment',
      navTarget: searchRecruitmentTarget,
      packId: 'player_search',
      prerequisiteMissionIds: ['player_search_clubs'],
      priority: 80,
      programId: GuidanceProgramIds.player,
      rewardText: 'Vous repérez aussi les opportunités de recrutement visibles dans l’app.',
      shortDescription: 'Explorez les annonces recrutement.',
      title: 'Explorer le recrutement',
      tutorialTarget: searchRecruitmentTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir vos alertes', 'Comprendre comment retrouver des résultats plus tard'],
      audience: { roleKeys: ['player'] },
      completionMode: 'manual_fallback',
      completionSignal: { routeName: RouteNames.SearchAlerts, type: 'route' },
      id: 'player_search_alerts',
      longDescription: 'Les alertes et repères de recherche vous aident à ne pas repartir de zéro. C’est un levier pratique pour un usage régulier.',
      module: 'search',
      navTarget: { routeName: RouteNames.SearchAlerts },
      packId: 'player_search',
      prerequisiteMissionIds: ['player_search_recruitment'],
      priority: 90,
      programId: GuidanceProgramIds.player,
      rewardText: 'Vous savez comment prolonger une recherche dans le temps.',
      shortDescription: 'Repérez l’espace des alertes de recherche.',
      title: 'Découvrir les alertes',
    }),
    mission({
      actionsToTry: ['Depuis une recherche ou un détail, lancer une participation'],
      audience: { roleKeys: ['player'] },
      completionMode: 'auto',
      completionSignal: { key: 'event.participation.created', type: 'action' },
      id: 'player_participate_event',
      longDescription: 'Participer à un événement est un vrai cap: vous passez de la découverte à l’action concrète dans l’app.',
      module: 'event',
      navTarget: searchEventsTarget,
      packId: 'player_actions',
      prerequisiteMissionIds: ['player_search_alerts'],
      priority: 100,
      programId: GuidanceProgramIds.player,
      rewardText: 'Vous validez le parcours joueur le plus concret de FoundClub.',
      shortDescription: 'Demandez à participer à un événement.',
      title: 'Participer à un événement',
    }),
    mission({
      actionsToTry: ['Ouvrir votre fiche profil publique', 'Voir ce qu’un autre utilisateur perçoit'],
      audience: { roleKeys: ['player'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.UserDetails, type: 'route' },
      id: 'player_view_public_profile',
      longDescription: 'Consulter votre fiche publique permet de vérifier ce qui est visible et comment votre identité sportive ressort dans l’app.',
      module: 'profile',
      navTarget: {
        params: {
          screen: RouteNames.UserDetails,
        },
        routeName: RouteNames.ProfileStack,
      },
      packId: 'player_actions',
      prerequisiteMissionIds: ['player_participate_event'],
      priority: 110,
      programId: GuidanceProgramIds.player,
      rewardText: 'Vous maîtrisez mieux votre présence visible dans l’écosystème FoundClub.',
      shortDescription: 'Consultez votre fiche publique.',
      title: 'Voir mon profil public',
    }),
    mission({
      actionsToTry: ['Ouvrir vos licences ou paiements personnels si disponibles'],
      audience: { roleKeys: ['player'] },
      completionMode: 'manual_fallback',
      completionSignal: { routeName: RouteNames.MyLicense, type: 'route' },
      id: 'player_open_license',
      longDescription: 'Si votre club utilise les licences et cotisations dans FoundClub, cet espace devient votre point de repère administratif.',
      module: 'license',
      navTarget: { routeName: RouteNames.MyLicense },
      packId: 'player_actions',
      prerequisiteMissionIds: ['player_view_public_profile'],
      priority: 120,
      programId: GuidanceProgramIds.player,
      rewardText: 'Vous savez aussi où retrouver votre suivi administratif personnel.',
      shortDescription: 'Ouvrez l’espace licence personnel.',
      title: 'Explorer ma licence',
    }),
    mission({
      actionsToTry: ['Basculer vers League', 'Observer le dashboard et son vocabulaire'],
      audience: { requiresLeagueMode: true, roleKeys: ['player'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.LeagueDashboard, type: 'route' },
      id: 'player_open_league',
      longDescription: 'League ajoute une couche compétitive spécifique. Même une première visite aide à comprendre ce que ce mode apporte au parcours joueur.',
      module: 'league',
      navTarget: leagueDashboardTarget,
      packId: 'player_actions',
      prerequisiteMissionIds: ['player_open_license'],
      priority: 130,
      programId: GuidanceProgramIds.player,
      rewardText: 'Vous avez exploré l’ouverture League liée à votre rôle joueur.',
      shortDescription: 'Découvrir l’entrée League.',
      title: 'Ouvrir League',
    }),

    mission({
      actionsToTry: ['Vérifier votre identité coach dans le profil'],
      audience: { roleKeys: ['coach'] },
      completionMode: 'auto',
      completionSignal: { key: 'profileBasicsComplete', type: 'state' },
      id: 'coach_profile_basics',
      longDescription: 'Avant de piloter des équipes, vérifiez votre base profil. C’est aussi ce qui structure votre visibilité dans les demandes et les espaces club.',
      module: 'profile',
      navTarget: profileEditTarget,
      packId: 'coach_foundations',
      prerequisiteMissionIds: [],
      priority: 10,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Votre base coach est prête pour les autres outils.',
      shortDescription: 'Complétez votre profil entraîneur.',
      title: 'Préparer mon profil coach',
      tutorialTarget: profileEditTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir l’onglet planning', 'Repérer le résumé haut de page'],
      audience: { roleKeys: ['coach'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.MyEventList, type: 'route' },
      id: 'coach_open_planning',
      longDescription: 'Le planning est le centre nerveux d’un entraîneur: événements, visibilité des réponses et accès aux actions de création.',
      module: 'planning',
      navTarget: planningTarget,
      packId: 'coach_foundations',
      prerequisiteMissionIds: ['coach_profile_basics'],
      priority: 20,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Vous avez retrouvé le hub quotidien le plus utile côté terrain.',
      shortDescription: 'Ouvrez le planning coach.',
      title: 'Aller dans le planning',
      tutorialTarget: planningTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir l’espace équipes', 'Repérer les équipes coachées'],
      audience: { requiresTrainingTeam: true, roleKeys: ['coach'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.MyTeamList, type: 'route' },
      id: 'coach_open_teams',
      longDescription: 'Votre espace équipes concentre les collectifs que vous encadrez et devient une porte d’entrée vers leur gestion.',
      module: 'team',
      navTarget: teamHubTarget,
      packId: 'coach_foundations',
      prerequisiteMissionIds: ['coach_open_planning'],
      priority: 30,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Vous savez où retrouver vos équipes coachées.',
      shortDescription: 'Ouvrez l’espace équipes.',
      title: 'Voir mes équipes',
    }),
    mission({
      actionsToTry: ['Ouvrir la messagerie', 'Repérer les conversations utiles au coaching'],
      audience: { roleKeys: ['coach'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.Chat, type: 'route' },
      id: 'coach_open_messages',
      longDescription: 'La messagerie est essentielle pour l’organisation quotidienne: échanges directs, conversations équipe ou coordinations plus larges.',
      module: 'messaging',
      navTarget: messagingTarget,
      packId: 'coach_foundations',
      prerequisiteMissionIds: ['coach_open_teams'],
      priority: 40,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Vous avez identifié le centre de communication à utiliser au quotidien.',
      shortDescription: 'Explorer la messagerie.',
      title: 'Ouvrir la messagerie',
      tutorialTarget: messagingTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir les demandes', 'Observer la liste consolidée'],
      audience: { requiresRequestsContext: true, roleKeys: ['coach'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.RequestsHub, type: 'route' },
      id: 'coach_open_requests',
      longDescription: 'Le hub de demandes agrège adhésions, validations d’événements, sujets club et autres flux à traiter pour les rôles de gestion.',
      module: 'requests',
      navTarget: requestsTarget,
      packId: 'coach_operations',
      prerequisiteMissionIds: ['coach_open_messages'],
      priority: 50,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Vous savez où traiter les flux opérationnels sans naviguer à l’aveugle.',
      shortDescription: 'Ouvrir le hub des demandes.',
      title: 'Consulter les demandes',
      tutorialTarget: requestsTarget,
    }),
    mission({
      actionsToTry: ['Créer un événement depuis le planning ou le CTA dédié'],
      audience: { requiresTrainingTeam: true, roleKeys: ['coach'] },
      completionMode: 'manual_fallback',
      completionSignal: { key: 'event.created', type: 'action' },
      id: 'coach_create_event',
      longDescription: 'Créer un événement vous permet de vérifier le parcours coach jusqu’à l’action concrète: entraînement, match, détection ou autre besoin terrain.',
      module: 'event',
      navTarget: planningTarget,
      packId: 'coach_operations',
      prerequisiteMissionIds: ['coach_open_requests'],
      priority: 60,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Vous maîtrisez déjà une action centrale du rôle entraîneur.',
      shortDescription: 'Créer un événement.',
      title: 'Créer un événement',
    }),
    mission({
      actionsToTry: ['Ouvrir le planning et repérer où modifier un événement existant'],
      audience: { requiresTrainingTeam: true, roleKeys: ['coach'] },
      completionMode: 'manual_fallback',
      completionSignal: { key: 'event.updated', type: 'action' },
      id: 'coach_edit_event',
      longDescription: 'La modification d’événement est un usage terrain récurrent. Cette mission vous amène au bon endroit pour pratiquer ce flux.',
      module: 'event',
      navTarget: planningTarget,
      packId: 'coach_operations',
      prerequisiteMissionIds: ['coach_create_event'],
      priority: 70,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Vous savez aussi corriger ou adapter le planning sans sortir de l’app.',
      shortDescription: 'Modifier un événement.',
      title: 'Mettre à jour un événement',
    }),
    mission({
      actionsToTry: ['Ouvrir la recherche événement', 'Repérer les filtres coach'],
      audience: { roleKeys: ['coach'] },
      completionMode: 'auto',
      completionSignal: { key: 'search.tab.events', type: 'interaction' },
      id: 'coach_search_events',
      longDescription: 'La recherche événement n’est pas réservée aux joueurs. Côté coach, elle sert aussi à surveiller des opportunités, détections et contextes extérieurs.',
      module: 'search',
      navTarget: searchEventsTarget,
      packId: 'coach_operations',
      prerequisiteMissionIds: ['coach_edit_event'],
      priority: 80,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Vous savez relire l’offre événementielle sous un angle coach.',
      shortDescription: 'Explorer la recherche événement.',
      title: 'Explorer les événements',
      tutorialTarget: searchEventsTarget,
    }),
    mission({
      actionsToTry: ['Changer le filtre du hub demandes', 'Comprendre la segmentation disponible'],
      audience: { requiresRequestFilter: 'team', requiresRequestsContext: true, roleKeys: ['coach'] },
      completionMode: 'auto',
      completionSignal: { key: 'requests.filter.team', type: 'interaction' },
      id: 'coach_filter_requests',
      longDescription: 'Le hub demandes devient plus efficace quand vous maîtrisez ses filtres. Cette mission vous pousse à explorer la segmentation par type.',
      module: 'requests',
      navTarget: {
        params: { initialFilter: 'team', source: 'guidance' },
        routeName: RouteNames.RequestsHub,
      },
      packId: 'coach_operations',
      prerequisiteMissionIds: ['coach_search_events'],
      priority: 90,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Vous gagnez en précision pour vos prochains traitements.',
      shortDescription: 'Filtrer les demandes.',
      title: 'Utiliser un filtre de demandes',
    }),
    mission({
      actionsToTry: ['Ouvrir les annonces de recrutement', 'Voir les besoins publiés par les clubs et équipes'],
      audience: { roleKeys: ['coach'] },
      completionMode: 'auto',
      completionSignal: { key: 'search.tab.recruitment', type: 'interaction' },
      id: 'coach_search_recruitment',
      longDescription: 'La recherche recrutement vous permet d’observer le marché et de mieux comprendre comment l’app structure les besoins de profils.',
      module: 'recruitment',
      navTarget: searchRecruitmentTarget,
      packId: 'coach_recruitment',
      prerequisiteMissionIds: ['coach_filter_requests'],
      priority: 100,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Vous avez exploré le versant découverte du recrutement.',
      shortDescription: 'Explorer les annonces de recrutement.',
      title: 'Ouvrir le recrutement',
      tutorialTarget: searchRecruitmentTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir l’assistant annonce', 'Repérer les étapes du wizard'],
      audience: { roleKeys: ['coach'] },
      completionMode: 'manual_fallback',
      completionSignal: { routeName: RouteNames.AdWizardAudienceType, type: 'route' },
      id: 'coach_open_ad_wizard',
      longDescription: 'Le wizard de recrutement est l’endroit où vous publiez un besoin structuré. Même une première ouverture suffit pour comprendre le parcours produit.',
      module: 'recruitment',
      navTarget: { routeName: RouteNames.AdWizardStack },
      packId: 'coach_recruitment',
      prerequisiteMissionIds: ['coach_search_recruitment'],
      priority: 110,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Vous connaissez le bon point d’entrée pour créer une annonce.',
      shortDescription: 'Ouvrir l’assistant annonce.',
      title: 'Préparer une annonce recrutement',
    }),
    mission({
      actionsToTry: ['Traiter une demande réelle si disponible', 'Observer les actions d’acceptation ou refus'],
      audience: { requiresRequestsContext: true, roleKeys: ['coach'] },
      completionMode: 'manual_fallback',
      completionSignal: { key: 'requests.processed', type: 'action' },
      id: 'coach_process_request',
      longDescription: 'Cette mission valide le passage du coach à un vrai traitement opérationnel dans le hub demandes.',
      module: 'requests',
      navTarget: requestsTarget,
      packId: 'coach_recruitment',
      prerequisiteMissionIds: ['coach_open_ad_wizard'],
      priority: 120,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Vous avez validé une action métier coach très concrète.',
      shortDescription: 'Traiter une demande.',
      title: 'Répondre à une demande',
    }),
    mission({
      actionsToTry: ['Ouvrir les cotisations ou licences si votre club les utilise'],
      audience: { requiresClub: true, roleKeys: ['coach'] },
      completionMode: 'manual_fallback',
      completionSignal: { routeName: RouteNames.ClubLicenses, type: 'route' },
      id: 'coach_open_licenses',
      longDescription: 'Dans certains contextes, les entraîneurs ont besoin de lire ou suivre les statuts cotisation/licence. Cette mission vous fait découvrir l’outil.',
      module: 'license',
      navTarget: {
        params: (context) => ({
          params: { clubId: context.clubId },
          screen: RouteNames.ClubLicenses,
        }),
        routeName: RouteNames.ClubStack,
      },
      packId: 'coach_recruitment',
      prerequisiteMissionIds: ['coach_process_request'],
      priority: 130,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Vous savez où retrouver le versant administratif lié à vos équipes.',
      shortDescription: 'Explorer l’espace cotisations.',
      title: 'Voir les cotisations',
    }),
    mission({
      actionsToTry: ['Ouvrir les réservations', 'Voir comment le module s’organise'],
      audience: { roleKeys: ['coach'] },
      completionMode: 'manual_fallback',
      completionSignal: { key: 'search.tab.reservations', type: 'interaction' },
      id: 'coach_open_reservations',
      longDescription: 'Le module réservations complète le paysage coach quand des créneaux ou installations doivent être consultés.',
      module: 'reservation',
      navTarget: searchReservationsTarget,
      packId: 'coach_recruitment',
      prerequisiteMissionIds: ['coach_open_licenses'],
      priority: 140,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Vous avez exploré une surface moins quotidienne mais utile.',
      shortDescription: 'Découvrir les réservations.',
      title: 'Explorer les réservations',
      tutorialTarget: searchReservationsTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir vos alertes et comprendre leur intérêt'],
      audience: { roleKeys: ['coach'] },
      completionMode: 'manual_fallback',
      completionSignal: { routeName: RouteNames.SearchAlerts, type: 'route' },
      id: 'coach_open_alerts',
      longDescription: 'Les alertes évitent de refaire les mêmes recherches. C’est un détail produit utile quand l’usage devient plus régulier.',
      module: 'search',
      navTarget: { routeName: RouteNames.SearchAlerts },
      packId: 'coach_recruitment',
      prerequisiteMissionIds: ['coach_open_reservations'],
      priority: 150,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Vous avez vu comment FoundClub peut aussi travailler en mémoire pour vous.',
      shortDescription: 'Ouvrir les alertes de recherche.',
      title: 'Comprendre les alertes',
    }),
    mission({
      actionsToTry: ['Passer par le dashboard League', 'Lire les cartes et signaux disponibles'],
      audience: { requiresLeagueMode: true, roleKeys: ['coach'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.LeagueDashboard, type: 'route' },
      id: 'coach_open_league',
      longDescription: 'League complète le rôle coach avec une couche compétitive spécifique. Une première visite suffit pour comprendre les grands repères du module.',
      module: 'league',
      navTarget: leagueDashboardTarget,
      packId: 'coach_recruitment',
      prerequisiteMissionIds: ['coach_open_alerts'],
      priority: 160,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Vous avez couvert aussi la porte d’entrée League côté coach.',
      shortDescription: 'Ouvrir League.',
      title: 'Découvrir League',
    }),

    // --- Tour guide coach (declenche a la fin de l'onboarding depuis l'ecran Welcome) ---
    // Etapes lineaires (chaque etape debloque la suivante), priorites hautes (300+) pour ne
    // jamais perturber la mission courante d'un coach existant. Toutes visibles des l'inscription
    // (aucun prerequis d'equipe/club) afin que le tour se joue meme sans equipe encore creee.
    mission({
      actionsToTry: ['Parcourir les etapes du tour guide', 'Reperer la prochaine action proposee'],
      audience: { roleKeys: ['coach'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.MissionCenter, type: 'route' },
      id: 'coach_tour_welcome',
      longDescription: "Bienvenue dans FoundClub. Ce tour guide t'accompagne sur tes premiers reflexes de coach : creer un evenement, suivre les presences, preparer une compo, ouvrir ton planning, ton equipe et ta messagerie. Chaque etape est facultative et tu peux la passer a tout moment.",
      module: 'intro',
      navTarget: { routeName: RouteNames.MissionCenter },
      packId: 'coach_tour',
      prerequisiteMissionIds: [],
      priority: 300,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Tu sais ou retrouver ton tour guide et le rejouer quand tu veux.',
      shortDescription: 'Demarre ton tour guide de coach.',
      title: 'Bienvenue dans FoundClub',
    }),
    mission({
      actionsToTry: ["Ouvrir l'assistant evenement", "Choisir un type d'evenement"],
      audience: { roleKeys: ['coach'] },
      completionMode: 'manual_fallback',
      completionSignal: { key: 'event.created', type: 'action' },
      id: 'coach_tour_create_event',
      longDescription: "Tout commence par un evenement. L'assistant te guide pour creer ton premier entrainement, match ou detection : choisis un type, renseigne les infos cles et publie. C'est le point de depart de la vie de ton equipe sur FoundClub.",
      module: 'event',
      navTarget: eventWizardTarget,
      packId: 'coach_tour',
      prerequisiteMissionIds: ['coach_tour_welcome'],
      priority: 310,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Tu maitrises le geste central du coach : creer un evenement.',
      shortDescription: 'Cree ton premier evenement.',
      title: 'Creer ton premier evenement',
      tutorialTarget: eventWizardTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir un evenement depuis ton planning', 'Reperer les presences et les participants'],
      audience: { roleKeys: ['coach'] },
      completionMode: 'manual_fallback',
      completionSignal: { routeName: RouteNames.EventDetails, type: 'route' },
      id: 'coach_tour_follow_event',
      longDescription: "Une fois l'evenement cree, ouvre son detail depuis ton planning pour suivre les reponses de presence, les participants attendus et les infos logistiques. C'est ici que tu piloteras la preparation de chaque rendez-vous.",
      module: 'event',
      navTarget: planningTarget,
      packId: 'coach_tour',
      prerequisiteMissionIds: ['coach_tour_create_event'],
      priority: 320,
      programId: GuidanceProgramIds.coach,
      rewardText: "Tu sais suivre les presences et les participants d'un evenement.",
      shortDescription: 'Suis les presences de ton evenement.',
      title: 'Suivre ton evenement',
    }),
    mission({
      actionsToTry: ['Deplacer des joueurs fictifs sur le terrain', 'Tester une organisation sans rien publier'],
      audience: { roleKeys: ['coach'] },
      completionMode: 'manual_fallback',
      completionSignal: { routeName: RouteNames.TacticalBoardV2, type: 'route' },
      id: 'coach_tour_composition',
      longDescription: "Prepare une composition dans un bac a sable : le terrain est rempli de joueurs fictifs pour t'entrainer sans aucune ecriture serveur. Publier une vraie compo depuis un evenement demande ensuite une offre payante.",
      module: 'tactical',
      navTarget: compositionSimulationTarget,
      packId: 'coach_tour',
      premiumFeature: true,
      prerequisiteMissionIds: ['coach_tour_follow_event'],
      priority: 330,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Tu as teste le board de composition en mode apercu.',
      shortDescription: 'Teste une compo en mode apercu.',
      title: 'Preparer une composition',
    }),
    mission({
      actionsToTry: ['Ouvrir ton planning', 'Reperer la vue semaine et les creneaux'],
      audience: { roleKeys: ['coach'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.MyEventList, type: 'route' },
      id: 'coach_tour_planning',
      longDescription: "Ton planning regroupe tous tes evenements a venir et te donne une lecture claire de la semaine. La reservation d'installations et de creneaux club fait partie des options qui s'ouvrent avec une offre payante.",
      module: 'planning',
      navTarget: planningTarget,
      packId: 'coach_tour',
      premiumFeature: true,
      prerequisiteMissionIds: ['coach_tour_composition'],
      priority: 340,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Tu sais ou lire ton planning au quotidien.',
      shortDescription: 'Ouvre ton planning.',
      title: 'Ton planning',
      tutorialTarget: planningTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir ton espace equipe', "Reperer l'invitation des joueurs"],
      audience: { roleKeys: ['coach'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.MyTeamList, type: 'route' },
      id: 'coach_tour_team',
      longDescription: "Ton espace equipe centralise tes joueurs et l'invitation de nouveaux membres. Tu peux animer une premiere equipe gratuitement ; ajouter une seconde equipe demande une offre payante.",
      module: 'team',
      navTarget: teamHubTarget,
      packId: 'coach_tour',
      premiumFeature: true,
      prerequisiteMissionIds: ['coach_tour_planning'],
      priority: 350,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Tu sais ou inviter et gerer tes joueurs.',
      shortDescription: 'Ouvre ton equipe et invite des joueurs.',
      title: 'Ton equipe',
    }),
    mission({
      actionsToTry: ['Ouvrir ta messagerie', "Reperer les conversations d'equipe"],
      audience: { roleKeys: ['coach'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.Chat, type: 'route' },
      id: 'coach_tour_messaging',
      longDescription: "La messagerie te permet d'echanger avec tes joueurs et de coordonner chaque rendez-vous. Les groupes de discussion a l'echelle du club s'ouvrent avec une offre payante.",
      module: 'messaging',
      navTarget: messagingTarget,
      packId: 'coach_tour',
      premiumFeature: true,
      prerequisiteMissionIds: ['coach_tour_team'],
      priority: 360,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Tu sais ou coordonner ton equipe au quotidien.',
      shortDescription: 'Ouvre ta messagerie.',
      title: 'Ta messagerie',
      tutorialTarget: messagingTarget,
    }),
    mission({
      actionsToTry: ['Comparer les offres Free, Team et Club', 'Reperer ce que chaque offre debloque'],
      audience: { roleKeys: ['coach'] },
      completionMode: 'manual_fallback',
      completionSignal: { routeName: RouteNames.GuideOffersRecap, type: 'route' },
      id: 'coach_tour_offers_recap',
      longDescription: 'Pour finir, retrouve le recapitulatif des offres FoundClub : ce qui est inclus en gratuit et ce que Team et Club ajoutent pour ton organisation. Tu pourras y revenir a tout moment depuis ton profil.',
      module: 'subscription',
      navTarget: offersRecapTarget,
      packId: 'coach_tour',
      prerequisiteMissionIds: ['coach_tour_messaging'],
      priority: 370,
      programId: GuidanceProgramIds.coach,
      rewardText: 'Tu connais les offres FoundClub et ou les retrouver.',
      shortDescription: 'Vois le recap des offres FoundClub.',
      title: 'Recap des offres',
    }),

    mission({
      actionsToTry: ['Ouvrir votre espace club ou multisport dès l’accueil'],
      audience: { requiresManagedClub: true, roleKeys: ['president'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.Club, type: 'route' },
      id: 'president_open_club',
      longDescription: 'Le dirigeant doit savoir rejoindre immédiatement son espace de pilotage. C’est la base avant d’explorer les modules plus fins.',
      module: 'club',
      navTarget: {
        params: (context) => ({
          params: { clubId: context.clubId },
          screen: RouteNames.Club,
        }),
        routeName: RouteNames.ClubStack,
      },
      packId: 'president_foundations',
      prerequisiteMissionIds: [],
      priority: 10,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous avez retrouvé votre cockpit club principal.',
      shortDescription: 'Ouvrez votre espace club.',
      title: 'Accéder à mon club',
    }),
    mission({
      actionsToTry: ['Ouvrir les demandes globales', 'Observer les catégories disponibles'],
      audience: { requiresRequestsContext: true, roleKeys: ['president'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.RequestsHub, type: 'route' },
      id: 'president_open_requests',
      longDescription: 'Le hub demandes agrège une grande partie des flux opérationnels d’un dirigeant. Le connaître tôt évite de se disperser dans l’app.',
      module: 'requests',
      navTarget: requestsTarget,
      packId: 'president_foundations',
      prerequisiteMissionIds: ['president_open_club'],
      priority: 20,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous avez identifié un centre de traitement transversal très important.',
      shortDescription: 'Ouvrir le hub des demandes.',
      title: 'Voir toutes les demandes',
      tutorialTarget: requestsTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir le profil dirigeant', 'Repérer les actions rapides du profil'],
      audience: { roleKeys: ['president'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.Profile, type: 'route' },
      id: 'president_open_profile',
      longDescription: 'Votre espace profil n’est pas seulement personnel: il héberge aussi des points d’accès utiles, du changement de compte aux parcours d’aide.',
      module: 'profile',
      navTarget: profileTarget,
      packId: 'president_foundations',
      prerequisiteMissionIds: ['president_open_requests'],
      priority: 30,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous avez repéré le centre personnel du rôle dirigeant.',
      shortDescription: 'Ouvrir le profil FoundClub.',
      title: 'Explorer le profil',
      tutorialTarget: profileTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir la messagerie', 'Observer les canaux utiles au pilotage'],
      audience: { roleKeys: ['president'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.Chat, type: 'route' },
      id: 'president_open_messages',
      longDescription: 'Le dirigeant utilise souvent la messagerie comme interface de coordination. Cette mission la replace explicitement dans votre boite a outils de pilotage.',
      module: 'messaging',
      navTarget: messagingTarget,
      packId: 'president_foundations',
      prerequisiteMissionIds: ['president_open_profile'],
      priority: 40,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous avez connecté la coordination humaine au reste du pilotage.',
      shortDescription: 'Ouvrez la messagerie FoundClub.',
      title: 'Consulter la messagerie',
      tutorialTarget: messagingTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir le planning', 'Observer l’articulation planning / événements'],
      audience: { roleKeys: ['president'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.MyEventList, type: 'route' },
      id: 'president_open_planning',
      longDescription: 'Le planning reste un point de commandement, même pour un dirigeant. Il donne une lecture opérationnelle de la vie terrain du club.',
      module: 'planning',
      navTarget: planningTarget,
      packId: 'president_operations',
      prerequisiteMissionIds: ['president_open_messages'],
      priority: 50,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous savez où lire l’activité événementielle du club.',
      shortDescription: 'Aller dans le planning.',
      title: 'Ouvrir le planning',
      tutorialTarget: planningTarget,
    }),
    mission({
      actionsToTry: ['Créer un événement depuis le planning ou le CTA prévu'],
      audience: { roleKeys: ['president'] },
      completionMode: 'manual_fallback',
      completionSignal: { key: 'event.created', type: 'action' },
      id: 'president_create_event',
      longDescription: 'Créer un événement valide un geste fondamental de pilotage club et vous montre comment l’app structure ce parcours côté dirigeant.',
      module: 'event',
      navTarget: planningTarget,
      packId: 'president_operations',
      prerequisiteMissionIds: ['president_open_planning'],
      priority: 60,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous avez couvert un premier vrai flux métier de direction.',
      shortDescription: 'Créer un événement club.',
      title: 'Créer un événement',
    }),
    mission({
      actionsToTry: ['Depuis le planning, ouvrir puis modifier un événement'],
      audience: { roleKeys: ['president'] },
      completionMode: 'manual_fallback',
      completionSignal: { key: 'event.updated', type: 'action' },
      id: 'president_edit_event',
      longDescription: 'La modification d’événement est un usage récurrent en pilotage club. Cette mission vous amène au bon hub pour pratiquer cette action.',
      module: 'event',
      navTarget: planningTarget,
      packId: 'president_operations',
      prerequisiteMissionIds: ['president_create_event'],
      priority: 70,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous savez réagir à la réalité terrain depuis FoundClub.',
      shortDescription: 'Modifier un événement existant.',
      title: 'Mettre à jour un événement',
    }),
    mission({
      actionsToTry: ['Ouvrir vos équipes ou votre espace de structure'],
      audience: { roleKeys: ['president'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.MyTeamList, type: 'route' },
      id: 'president_open_structure',
      longDescription: 'Selon votre contexte, l’onglet équipes ou l’espace club multisport devient un point d’accès crucial pour naviguer dans la structure.',
      module: 'team',
      navTarget: teamHubTarget,
      packId: 'president_operations',
      prerequisiteMissionIds: ['president_edit_event'],
      priority: 80,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous avez relié le pilotage global à la structure humaine du club.',
      shortDescription: 'Explorer la structure club/équipes.',
      title: 'Voir la structure du club',
    }),
    mission({
      actionsToTry: ['Ouvrir les demandes filtrées côté équipe'],
      audience: { requiresRequestFilter: 'team', requiresRequestsContext: true, roleKeys: ['president'] },
      completionMode: 'auto',
      completionSignal: { key: 'requests.filter.team', type: 'interaction' },
      id: 'president_filter_team_requests',
      longDescription: 'Le dirigeant gagne en lisibilité quand il sait isoler les demandes liées aux équipes. Cette mission vous fait pratiquer ce premier filtre.',
      module: 'requests',
      navTarget: {
        params: { initialFilter: 'team', source: 'guidance' },
        routeName: RouteNames.RequestsHub,
      },
      packId: 'president_requests_recruitment',
      prerequisiteMissionIds: ['president_open_structure'],
      priority: 90,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous commencez à maîtriser le tri intelligent du hub demandes.',
      shortDescription: 'Filtrer les demandes équipe.',
      title: 'Utiliser le filtre équipe',
    }),
    mission({
      actionsToTry: ['Ouvrir les demandes filtrées côté club ou événement'],
      audience: { requiresRequestFilter: 'event', requiresRequestsContext: true, roleKeys: ['president'] },
      completionMode: 'auto',
      completionSignal: { key: 'requests.filter.event', type: 'interaction' },
      id: 'president_filter_event_requests',
      longDescription: 'Le filtre événement vous permet de focaliser la lecture sur les validations, participations et besoins liés au planning.',
      module: 'requests',
      navTarget: {
        params: { initialFilter: 'event', source: 'guidance' },
        routeName: RouteNames.RequestsHub,
      },
      packId: 'president_requests_recruitment',
      prerequisiteMissionIds: ['president_filter_team_requests'],
      priority: 100,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous avez couvert un deuxième axe important de lecture du hub.',
      shortDescription: 'Filtrer les demandes événement.',
      title: 'Utiliser le filtre événement',
    }),
    mission({
      actionsToTry: ['Ouvrir le recrutement', 'Lire les annonces existantes'],
      audience: { roleKeys: ['president'] },
      completionMode: 'auto',
      completionSignal: { key: 'search.tab.recruitment', type: 'interaction' },
      id: 'president_open_recruitment',
      longDescription: 'Le recrutement est un levier de pilotage club, pas seulement une découverte joueur. Cette mission vous connecte à cette surface produit.',
      module: 'recruitment',
      navTarget: searchRecruitmentTarget,
      packId: 'president_requests_recruitment',
      prerequisiteMissionIds: ['president_filter_event_requests'],
      priority: 110,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous avez intégré le recrutement à votre carte mentale dirigeant.',
      shortDescription: 'Explorer le recrutement.',
      title: 'Ouvrir le recrutement',
      tutorialTarget: searchRecruitmentTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir l’assistant annonce', 'Observer les étapes disponibles'],
      audience: { roleKeys: ['president'] },
      completionMode: 'manual_fallback',
      completionSignal: { routeName: RouteNames.AdWizardAudienceType, type: 'route' },
      id: 'president_open_ad_wizard',
      longDescription: 'Le wizard de recrutement structure la publication d’un besoin. Cette mission vous amène au bon endroit pour maîtriser ce parcours dirigeant.',
      module: 'recruitment',
      navTarget: { routeName: RouteNames.AdWizardStack },
      packId: 'president_requests_recruitment',
      prerequisiteMissionIds: ['president_open_recruitment'],
      priority: 120,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous savez où publier un besoin ciblé dans l’app.',
      shortDescription: 'Ouvrir l’assistant annonce.',
      title: 'Préparer une annonce recrutement',
    }),
    mission({
      actionsToTry: ['Traiter une demande réelle depuis le hub'],
      audience: { requiresRequestsContext: true, roleKeys: ['president'] },
      completionMode: 'manual_fallback',
      completionSignal: { key: 'requests.processed', type: 'action' },
      id: 'president_process_request',
      longDescription: 'Le pilotage club prend tout son sens quand vous traitez un flux réel. Cette mission vous pousse à valider une action métier concrète.',
      module: 'requests',
      navTarget: requestsTarget,
      packId: 'president_requests_recruitment',
      prerequisiteMissionIds: ['president_open_ad_wizard'],
      priority: 130,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous avez validé un véritable traitement dirigeant dans FoundClub.',
      shortDescription: 'Traiter une demande.',
      title: 'Répondre à une demande',
    }),
    mission({
      actionsToTry: ['Ouvrir l’espace cotisations', 'Observer paiements, relances et échéances'],
      audience: { requiresClub: true, roleKeys: ['president'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.ClubLicenses, type: 'route' },
      id: 'president_open_licenses',
      longDescription: 'Les cotisations et licences font partie des surfaces avancées les plus structurantes pour un dirigeant. Cette mission vous y conduit directement.',
      module: 'license',
      navTarget: {
        params: (context) => ({
          params: { clubId: context.clubId },
          screen: RouteNames.ClubLicenses,
        }),
        routeName: RouteNames.ClubStack,
      },
      packId: 'president_finance_structure',
      prerequisiteMissionIds: ['president_process_request'],
      priority: 140,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous avez découvert le volet financier/opérationnel du club.',
      shortDescription: 'Explorer les cotisations.',
      title: 'Ouvrir les cotisations',
    }),
    mission({
      actionsToTry: ['Ouvrir les installations', 'Repérer le module structurel du club'],
      audience: { roleKeys: ['president'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.FacilityList, type: 'route' },
      id: 'president_open_facilities',
      longDescription: 'Le module installations matérialise la dimension structurelle du club dans FoundClub. Cette mission vous montre où il vit.',
      module: 'facility',
      navTarget: { routeName: RouteNames.FacilityList },
      packId: 'president_finance_structure',
      prerequisiteMissionIds: ['president_open_licenses'],
      priority: 150,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous avez ajouté les surfaces infrastructure à votre carte produit.',
      shortDescription: 'Découvrir les installations.',
      title: 'Voir les installations',
    }),
    mission({
      actionsToTry: ['Ouvrir les réservations', 'Observer le module créneaux / réservations'],
      audience: { roleKeys: ['president'] },
      completionMode: 'auto',
      completionSignal: { key: 'search.tab.reservations', type: 'interaction' },
      id: 'president_open_reservations',
      longDescription: 'Le module réservations complète souvent les besoins d’un dirigeant autour des créneaux, besoins d’occupation et coordination des espaces.',
      module: 'reservation',
      navTarget: searchReservationsTarget,
      packId: 'president_finance_structure',
      prerequisiteMissionIds: ['president_open_facilities'],
      priority: 160,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous avez exploré le parcours réservation associé à la gestion club.',
      shortDescription: 'Explorer les réservations.',
      title: 'Ouvrir les réservations',
      tutorialTarget: searchReservationsTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir la recherche clubs', 'Comparer comment le club ressort publiquement'],
      audience: { roleKeys: ['president'] },
      completionMode: 'auto',
      completionSignal: { key: 'search.tab.clubs', type: 'interaction' },
      id: 'president_open_public_club_search',
      longDescription: 'La recherche clubs donne au dirigeant une lecture plus “vitrine” de l’écosystème FoundClub et de la place de son club dans cet ensemble.',
      module: 'search',
      navTarget: searchClubsTarget,
      packId: 'president_advanced',
      prerequisiteMissionIds: ['president_open_reservations'],
      priority: 170,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous avez couvert le regard externe/public sur le club.',
      shortDescription: 'Voir le club côté recherche.',
      title: 'Explorer la recherche clubs',
      tutorialTarget: searchClubsTarget,
    }),
    mission({
      actionsToTry: ['Ouvrir les alertes de recherche', 'Repérer l’intérêt des surveillances récurrentes'],
      audience: { roleKeys: ['president'] },
      completionMode: 'manual_fallback',
      completionSignal: { routeName: RouteNames.SearchAlerts, type: 'route' },
      id: 'president_open_alerts',
      longDescription: 'Les alertes permettent de prolonger une recherche ou un suivi. C’est un détail produit qui devient très utile dans un usage expert.',
      module: 'search',
      navTarget: { routeName: RouteNames.SearchAlerts },
      packId: 'president_advanced',
      prerequisiteMissionIds: ['president_open_public_club_search'],
      priority: 180,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous avez ajouté un outil de veille à votre arsenal.',
      shortDescription: 'Découvrir les alertes de recherche.',
      title: 'Comprendre les alertes',
    }),
    mission({
      actionsToTry: ['Passer sur League', 'Lire les cartes et repères du dashboard'],
      audience: { requiresLeagueMode: true, roleKeys: ['president'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.LeagueDashboard, type: 'route' },
      id: 'president_open_league',
      longDescription: 'League fait partie de la surface globale FoundClub. En tant que dirigeant, cette mission vous permet de comprendre où ce module s’insère dans votre pilotage.',
      module: 'league',
      navTarget: leagueDashboardTarget,
      packId: 'president_advanced',
      prerequisiteMissionIds: ['president_open_alerts'],
      priority: 190,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous avez couvert aussi le pan League de votre boite a outils dirigeant.',
      shortDescription: 'Ouvrir FoundClub League.',
      title: 'Découvrir League',
    }),
    mission({
      actionsToTry: ['Ouvrir le centre des missions', 'Explorer les packs restants ou rejouer un guide'],
      audience: { roleKeys: ['president'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.MissionCenter, type: 'route' },
      id: 'president_open_atlas',
      longDescription: 'Le centre des missions n est pas qu un onboarding. C est aussi votre vue complete pour reviser, relancer des guides et verifier que vous connaissez toute la palette dirigeant.',
      module: 'guidance',
      navTarget: { routeName: RouteNames.MissionCenter },
      packId: 'president_advanced',
      prerequisiteMissionIds: ['president_open_league'],
      priority: 200,
      programId: GuidanceProgramIds.president,
      rewardText: 'Vous bouclez le parcours dirigeant jusque dans ses surfaces d’aide et de maîtrise.',
      shortDescription: 'Ouvrir toutes les missions.',
      title: 'Explorer toutes les missions FoundClub',
    }),

    mission({
      actionsToTry: ['Ouvrir le dashboard League', 'Repérer les cartes principales'],
      audience: { requiresLeagueMode: true, roleKeys: ['player', 'coach', 'president'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.LeagueDashboard, type: 'route' },
      id: 'league_open_dashboard',
      longDescription: 'Le dashboard League donne la vue d’ensemble compétitive: état actuel, signaux utiles et raccourcis centraux du module.',
      module: 'league',
      navTarget: leagueDashboardTarget,
      packId: 'league_intro',
      prerequisiteMissionIds: [],
      priority: 10,
      programId: GuidanceProgramIds.leagueIntro,
      rewardText: 'Vous avez localisé le hub principal de League.',
      shortDescription: 'Ouvrir le dashboard League.',
      title: 'Voir le dashboard League',
    }),
    mission({
      actionsToTry: ['Aller dans l’onglet squad ou effectif League'],
      audience: { requiresLeagueMode: true, roleKeys: ['player', 'coach', 'president'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.LeagueSquadTab, type: 'route' },
      id: 'league_open_squad',
      longDescription: 'L’espace squad centralise l’effectif, les rôles et les accès d’équipe propres à League.',
      module: 'league',
      navTarget: {
        params: { screen: RouteNames.LeagueSquadTab },
        routeName: RouteNames.LeagueHomeTab,
      },
      packId: 'league_intro',
      prerequisiteMissionIds: ['league_open_dashboard'],
      priority: 20,
      programId: GuidanceProgramIds.leagueIntro,
      rewardText: 'Vous avez repéré la surface effectif de League.',
      shortDescription: 'Ouvrir la squad League.',
      title: 'Explorer la squad',
    }),
    mission({
      actionsToTry: ['Ouvrir l’onglet match', 'Lire les signaux d’action League'],
      audience: { requiresLeagueMode: true, roleKeys: ['player', 'coach', 'president'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.LeagueMatchTab, type: 'route' },
      id: 'league_open_match_tab',
      longDescription: 'L’onglet match concentre l’activité compétitive en cours: propositions, matchs, validations et suites du cycle League.',
      module: 'league',
      navTarget: {
        params: { screen: RouteNames.LeagueMatchTab },
        routeName: RouteNames.LeagueHomeTab,
      },
      packId: 'league_intro',
      prerequisiteMissionIds: ['league_open_squad'],
      priority: 30,
      programId: GuidanceProgramIds.leagueIntro,
      rewardText: 'Vous savez où lire le rythme compétitif au jour le jour.',
      shortDescription: 'Ouvrir l’espace match League.',
      title: 'Explorer les matchs',
    }),
    mission({
      actionsToTry: ['Revenir a toutes les missions pour rejouer une mission League plus tard'],
      audience: { requiresLeagueMode: true, roleKeys: ['player', 'coach', 'president'] },
      completionMode: 'auto',
      completionSignal: { routeName: RouteNames.MissionCenter, type: 'route' },
      id: 'league_revisit_atlas',
      longDescription: 'Le centre des missions sert aussi de carte de rappel pour League. Cette mission ferme la boucle en vous montrant où revenir pour approfondir.',
      module: 'guidance',
      navTarget: { routeName: RouteNames.MissionCenter },
      packId: 'league_intro',
      prerequisiteMissionIds: ['league_open_match_tab'],
      priority: 40,
      programId: GuidanceProgramIds.leagueIntro,
      rewardText: 'Vous avez bouclé la découverte League avec un point de retour clair.',
      shortDescription: 'Retrouver League dans toutes les missions.',
      title: 'Revenir aux missions League',
    }),
  ],
});

export const getAllGuidanceMissionIds = () => guidanceCatalog.missions.map((item) => item.id);
export const getAllGuidancePackIds = () => guidanceCatalog.packs.map((item) => item.id);
