---
image: node:20-alpine
stages:
  - install_deps
  - Quality


# Jobs
.quality:
  stage: Quality
  only:
    - merge_requests
    - main
  before_script:
    - npm ci --cache .npm --prefer-offline
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - .npm/
    - policy: pull


linter:
  extends: .quality
  script:
    - npm run lint
  cache:
      policy: pull-push # We override the policy for one job


theme-contract:
  extends: .quality
  script:
    - npm run verify:theme-contract


type-check-no-regression:
  extends: .quality
  script:
    - npm run type-check:no-regression
  artifacts:
    when: always
    paths:
      - .tmp/typecheck-no-regression.json
      - .tmp/typecheck.log


type-check-report:
  extends: .quality
  allow_failure: true
  script:
    - npm run type-check:report
  artifacts:
    when: always
    paths:
      - .tmp/typecheck-report.json
      - .tmp/typecheck.log


jest-tests:
  extends: .quality
  script:
    - npm run test --passWithNoTests --ci



type:
  extends: .quality
  allow_failure: true
  script:
    - npm run type-check
