
auth.token=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

defaults.org=zolteam
defaults.project=faciliciti-app

defaults.url=https://sentry.io/
