/* eslint-disable jsdoc/require-jsdoc */
import { useNavigation, useRoute } from '@react-navigation/native';
import { useCallback, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  Alert,
  ScrollView,
  StyleSheet,
  Switch,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import {
  buildDetectionSplitPayload,
  buildDraftPayloadWithSplit,
  countRequestedPositions,
  MAX_DETECTION_TEAMS,
  SPLIT_BY,
  splitIntoTeams,
} from '@/domains/detection/detectionSplit';
import { withAlpha } from '@/theme/colors';
import useTheme from '@/theme/themeContext';

import Button from '@/components/atoms/button/Button';
import HeaderBackButton from '@/components/atoms/headerBackButton/HeaderBackButton';
import ScreenContainer from '@/components/templates/ScreenContainer';

import { RouteNames } from '@/navigation/routeNames';

import { useGetEventTeamComposition } from '@/services/event/eventQueries';
import { saveEventCompositionDraft } from '@/services/event/eventService';

/**
 * C-D — ECRAN 15 du pack composition : « Repartition automatique ».
 *
 * 🎯 CE QUE CET ECRAN CALCULE, ET POURQUOI IL NE REUTILISE PAS `generateDraft`
 * L'ancien hub a bien une « generation automatique » qui appelle le serveur
 * (`MultiTeamCompositionBoard.js:990-1026`). La mesure du 2026-08-14 montre
 * qu'elle ne repond PAS a la meme question :
 *   - `buildAutoGeneratedPack` (admin `:894-958`) rend un PLACEMENT SUR TERRAIN,
 *     joueur par slot de formation — c'est l'ecran 16 ;
 *   - l'ecran 15, lui, rend une CONSTITUTION D'EQUIPES (qui joue avec qui) ;
 *   - et il ne lit ni `splitBy`, ni `memberMode`, ni `checkInFirst` : les trois
 *     reglages des ecrans 13 et 15 ne l'atteignent pas (0 lecteur mesure).
 * On reutilise donc ce qui doit l'etre — le MEME aller-retour serveur
 * (`saveEventCompositionDraft`), le MEME contrat `detectionSplit` — et le calcul
 * vit dans `domains/detection`, sous ses 4 temoins.
 *
 * ⛔ L'ancien hub n'est pas touche : ce lot ne modifie aucun fichier de
 * `views/tactical_v2/` (il disparait au lot C-F, pas avant).
 */

/** @type {any[]} */
const EMPTY_LIST = [];

const getPlayerId = (/** @type {any} */ player) => String(player?.documentId || player?.id || '');

function DetectionTeamsAuto() {
  const { Colors, Fonts } = useTheme();
  const { t } = useTranslation();
  const navigation = useNavigation();
  const route = useRoute();
  const insets = useSafeAreaInsets();

  /** @type {any} */
  const params = useMemo(() => route.params || {}, [route.params]);
  const {
    checkInFirst = false,
    eventId,
    memberMode,
    players: fallbackPlayers = EMPTY_LIST,
    presentIds = null,
    sport = 'football',
    teamId,
  } = params;

  const { data: teamComposition } = useGetEventTeamComposition(eventId, teamId, {
    enabled: Boolean(eventId),
  });

  const players = useMemo(() => {
    const fromServer = teamComposition?.eligiblePlayers;
    return Array.isArray(fromServer) && fromServer.length ? fromServer : fallbackPlayers;
  }, [fallbackPlayers, teamComposition?.eligiblePlayers]);

  const storedSplit = teamComposition?.detectionSplit || null;

  const [teamCount, setTeamCount] = useState(() => {
    const stored = Number(storedSplit?.teamCount);
    return Number.isFinite(stored) && stored >= 2 ? Math.min(stored, MAX_DETECTION_TEAMS) : 2;
  });
  const [splitByPosition, setSplitByPosition] = useState(
    () => storedSplit?.splitBy === SPLIT_BY.REQUESTED_POSITION,
  );
  const [isBusy, setIsBusy] = useState(false);

  const splitBy = splitByPosition ? SPLIT_BY.REQUESTED_POSITION : SPLIT_BY.NONE;

  // L'apercu montre le VRAI decoupage, pas une estimation : c'est exactement ce
  // que « Generer » enregistrera. Un apercu qui ment est pire que pas d'apercu.
  const preview = useMemo(() => splitIntoTeams({
    checkInFirst,
    memberMode,
    players,
    presentIds: presentIds || EMPTY_LIST,
    splitBy,
    teamCount,
  }), [checkInFirst, memberMode, players, presentIds, splitBy, teamCount]);

  const distributedCount = preview.teams.reduce((total, team) => total + team.playerIds.length, 0);
  const perTeam = teamCount > 0 ? Math.round(distributedCount / teamCount) : 0;

  const positionRows = useMemo(
    () => countRequestedPositions(players, teamCount),
    [players, teamCount],
  );

  const handleGenerate = useCallback(async () => {
    if (!eventId || !teamId || isBusy) return;
    setIsBusy(true);
    try {
      const detectionSplit = buildDetectionSplitPayload({
        checkInFirst,
        memberMode,
        players,
        presentIds: presentIds || players.map(getPlayerId),
        rounds: storedSplit?.rounds || EMPTY_LIST,
        splitBy,
        teamCount,
        teams: preview.teams,
      });

      await saveEventCompositionDraft(eventId, {
        draft: buildDraftPayloadWithSplit(teamComposition?.draft, detectionSplit),
        teamId,
      });
      Alert.alert(
        t('detection.alerts.saved.title'),
        t('detection.alerts.saved.message'),
        // AD01 (🚪) — MEME SUITE QUE L'ECRAN 14 : apres avoir genere les
        // equipes, on va les PLACER. `DetectionTeamsBoard` attendait derriere
        // sans un seul appelant. Seule la DESTINATION change ici.
        [{
          // @ts-ignore — `navigate` est bien la sur un ecran de pile.
          onPress: () => navigation.navigate(RouteNames.DetectionTeamsBoard, params),
          text: t('detection.alerts.ok'),
        }],
      );
    } catch (error) {
      Alert.alert(
        t('detection.alerts.error.title'),
        t('detection.alerts.error.save'),
      );
    } finally {
      setIsBusy(false);
    }
  }, [
    checkInFirst, eventId, isBusy, memberMode, navigation, params, players, presentIds,
    preview.teams, splitBy, storedSplit?.rounds, t, teamComposition?.draft, teamCount, teamId,
  ]);

  const renderPositionRow = (/** @type {any} */ row) => (
    <View
      key={row.position}
      style={[
        styles.positionRow,
        {
          backgroundColor: withAlpha(Colors.neutral00, 0.035),
          borderColor: withAlpha(Colors.neutral00, 0.09),
          // Le pack grise ces rangees a 45 % quand l'interrupteur est eteint :
          // elles decrivent alors une regle qui ne s'applique pas.
          opacity: splitByPosition ? 1 : 0.45,
        },
      ]}
    >
      <View style={styles.positionTexts}>
        <Text style={[Fonts.p2Bold, { color: Colors.neutral00 }]}>{row.position}</Text>
        <Text style={[Fonts.p4, { color: Colors.neutral300 }]}>
          {t('detection.teams.auto.positions.candidates', { count: row.count })}
        </Text>
      </View>
      <Text
        style={[
          Fonts.p4Bold,
          { color: row.onePerTeam ? Colors.primary500 : Colors.gold500 },
        ]}
      >
        {row.onePerTeam
          ? t('detection.teams.auto.positions.onePerTeam')
          : t('detection.teams.auto.positions.missing', { count: row.missing })}
      </Text>
    </View>
  );

  return (
    <ScreenContainer bgImage="bg2" bottomInsetMode="edge-to-edge" style={[styles.screen]}>
      <View style={styles.header}>
        <HeaderBackButton onPress={() => navigation.goBack()} />
        <View style={styles.headerTexts}>
          <Text style={[Fonts.h4Bold, { color: Colors.neutral00 }]}>
            {t('detection.teams.auto.title')}
          </Text>
          <Text numberOfLines={1} style={[Fonts.p3, { color: Colors.neutral300 }]}>
            {t('detection.teams.auto.subtitle', { registered: players.length, sport })}
          </Text>
        </View>
        {/* Fond neutre — meme motif que l'ecran 13, voir le commentaire la-bas. */}
        <View style={[styles.stepChip, { backgroundColor: withAlpha(Colors.neutral00, 0.08) }]}>
          <Text style={[Fonts.p4Bold, { color: Colors.primary100 }]}>
            {t('detection.teams.auto.chip')}
          </Text>
        </View>
      </View>

      <ScrollView
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
        style={styles.list}
      >
        <View
          style={[
            styles.counterCard,
            {
              backgroundColor: withAlpha(Colors.neutral00, 0.04),
              borderColor: withAlpha(Colors.neutral00, 0.1),
            },
          ]}
        >
          <Text style={[Fonts.p4, { color: Colors.neutral300 }]}>
            {t('detection.teams.auto.perTeam', { perTeam, registered: players.length })}
          </Text>
          <View style={styles.counterRow}>
            <TouchableOpacity
              accessibilityLabel="-"
              accessibilityRole="button"
              activeOpacity={0.8}
              onPress={() => setTeamCount((current) => Math.max(2, current - 1))}
              style={[styles.counterButton, { borderColor: Colors.primary500 }]}
            >
              <Text style={[Fonts.h3Bold, { color: Colors.primary500 }]}>-</Text>
            </TouchableOpacity>
            <View style={styles.counterValue}>
              <Text style={[Fonts.h1Bold, { color: Colors.neutral00 }]}>{teamCount}</Text>
              <Text style={[Fonts.p3, { color: Colors.neutral300 }]}>
                {t('detection.teams.auto.teamCount')}
              </Text>
            </View>
            <TouchableOpacity
              accessibilityLabel="+"
              accessibilityRole="button"
              activeOpacity={0.8}
              onPress={() => setTeamCount((current) => Math.min(MAX_DETECTION_TEAMS, current + 1))}
              style={[
                styles.counterButton,
                { backgroundColor: Colors.primary500, borderColor: Colors.primary500 },
              ]}
            >
              <Text style={[Fonts.h3Bold, { color: Colors.primary900 }]}>+</Text>
            </TouchableOpacity>
          </View>
        </View>

        <View
          style={[
            styles.switchCard,
            {
              backgroundColor: withAlpha(Colors.neutral00, 0.04),
              borderColor: withAlpha(Colors.neutral00, 0.1),
            },
          ]}
        >
          <View style={styles.positionTexts}>
            <Text style={[Fonts.p2Bold, { color: Colors.neutral00 }]}>
              {t('detection.teams.auto.splitBy.title')}
            </Text>
            <Text style={[Fonts.p3, { color: Colors.neutral300 }]}>
              {t('detection.teams.auto.splitBy.subtitle')}
            </Text>
          </View>
          <Switch
            accessibilityLabel={t('detection.teams.auto.splitBy.title')}
            onValueChange={setSplitByPosition}
            thumbColor={Colors.neutral00}
            trackColor={{ false: Colors.neutral700, true: Colors.primary500 }}
            value={splitByPosition}
          />
        </View>

        {/* Compteur reel, masque si zero : le pack interdit « 0 candidature »
            en vitrine. Une detection sans poste demande n'affiche donc rien. */}
        {positionRows.length ? (
          <>
            <Text style={[Fonts.p4, styles.sectionTitle, { color: Colors.neutral300 }]}>
              {t('detection.teams.auto.positions.title', {
                count: positionRows.length,
              }).toUpperCase()}
            </Text>
            {positionRows.map(renderPositionRow)}
          </>
        ) : null}

        <Text style={[Fonts.p4, styles.sectionTitle, { color: Colors.neutral300 }]}>
          {t('detection.teams.auto.previewTitle').toUpperCase()}
        </Text>
        <View style={[styles.previewCard, { borderColor: withAlpha(Colors.neutral00, 0.24) }]}>
          <Text style={[Fonts.p3, { color: Colors.neutral300 }]}>
            {distributedCount
              ? t('detection.teams.auto.preview.text', {
                perTeam,
                teams: teamCount,
                unassigned: preview.unassignedIds.length,
              })
              : t('detection.teams.auto.preview.empty')}
          </Text>
        </View>
      </ScrollView>

      <View style={[styles.footer, { paddingBottom: Math.max(insets.bottom, 12) }]}>
        <Button
          // @ts-ignore — `navigate` est bien la sur un ecran de pile.
          onPress={() => navigation.navigate(RouteNames.DetectionTeamsManual, params)}
          style={styles.footerGhost}
          title={t('detection.teams.auto.actions.manual')}
          variant="Secondary"
        />
        <Button
          disabled={!distributedCount}
          isLoading={isBusy}
          onPress={handleGenerate}
          style={styles.footerCta}
          title={t('detection.teams.auto.actions.generate')}
          variant="Primary"
        />
      </View>
    </ScreenContainer>
  );
}

const styles = StyleSheet.create({
  content: {
    paddingBottom: 24,
    paddingHorizontal: 16,
  },
  counterButton: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1.5,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  counterCard: {
    borderRadius: 20,
    borderWidth: 1,
    gap: 12,
    marginTop: 16,
    padding: 16,
  },
  counterRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  counterValue: {
    alignItems: 'center',
    flex: 1,
  },
  footer: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  footerCta: {
    flex: 1,
  },
  footerGhost: {
    width: 108,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingRight: 16,
    paddingVertical: 8,
  },
  headerTexts: {
    flex: 1,
  },
  list: {
    flex: 1,
  },
  positionRow: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    marginBottom: 8,
    minHeight: 44,
    padding: 12,
  },
  positionTexts: {
    flex: 1,
  },
  previewCard: {
    borderRadius: 16,
    borderStyle: 'dashed',
    borderWidth: 1,
    padding: 16,
  },
  screen: {
    flex: 1,
  },
  sectionTitle: {
    marginBottom: 8,
    marginTop: 16,
  },
  stepChip: {
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  switchCard: {
    alignItems: 'center',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
    padding: 16,
  },
});

export default DetectionTeamsAuto;
