default_platform(:ios)

# User values
ios_app_id = 'TE_REPLACE'
ios_app_scheme = 'TE_REPLACE'
ios_firebase_app_id = 'TE_REPLACE'
firebase_project_number = 0000

# System values
ios_directory = File.expand_path("..", Dir.pwd)
base_path = File.expand_path("..", ios_directory)
ios_workspace_path = "#{ios_directory}/#{ios_app_scheme}.xcworkspace"
ios_output_dir = File.expand_path("#{ios_directory}/output", base_path)
tester_udids_file = "tester_udids.txt"






#Only for local usage
# api_key = app_store_connect_api_key(
#   key_id: "2P9U5P95ZS",
#   issuer_id: "69a6de7b-c12b-47e3-e053-5b8c7c11a4d1",
#   key_filepath: "./fastlane/AuthKey_2P9U5P95ZS.p8",
#   duration: 1200, # optional (maximum 1200)
#   in_house: false # optional but may be required if using match/sigh
# )

before_all do
  if is_ci? && FastlaneCore::Helper.mac?
    setup_circle_ci
  end
end




platform :ios do

  before_all do
    setup_circle_ci
  end

  lane :nuke do |options|
    match_nuke(
      type: "adhoc",
      api_key: api_key,
      readonly: false
    )
  end

  lane :download_udids do
    firebase_app_distribution_get_udids(
      project_number: firebase_project_number,
      service_credentials_file: File.expand_path("./private-key.json", ios_directory),
      output_file: tester_udids_file
      )
  end

  lane :add_new_devices do
    register_devices(devices_file: tester_udids_file)
end

  lane :build_adhoc do |options|
    app_store_connect_api_key

    download_udids
    add_new_devices
    match(
      type: "adhoc",
      app_identifier: ios_app_id,
      force_for_new_devices: true,
      readonly: false
    )


    cocoapods(podfile: ios_directory)

    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: ENV["sigh_#{ios_app_id}_adhoc_team-id"],
      profile_name: ENV["sigh_#{ios_app_id}_adhoc_profile-name"],
      code_sign_identity: "iPhone Distribution"
    )

    gym(
      configuration: "Release",
      scheme: ios_app_scheme,
      export_method: "ad-hoc",
      workspace: ios_workspace_path,
      output_directory: ios_output_dir,
      clean: true,
      xcargs: "-UseModernBuildSystem=NO"
    )
  end

  lane :build_appstore do |options|
    app_store_connect_api_key

    match(
      type: "appstore",
      app_identifier: ios_app_id,
      readonly: false
    )


    cocoapods(podfile: ios_directory)

    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: ENV["sigh_#{ios_app_id}_appstore_team-id"],
      profile_name: ENV["sigh_#{ios_app_id}_appstore_profile-name"],
      code_sign_identity: "iPhone Distribution"
    )

    gym(
      configuration: "Release",
      scheme: ios_app_scheme,
      export_method: "app-store",
      workspace: ios_workspace_path,
      output_directory: ios_output_dir,
      clean: true,
      xcargs: "-UseModernBuildSystem=NO"
    )
  end

  lane :deploy_build do

    increment_build_number(
      build_number: ENV["TIMESTAMP"] # set a specific number
    )

    increment_version_number(
      version_number: "staging"
    )

    build_adhoc

    release = firebase_app_distribution(
      app: ios_firebase_app_id,
      service_credentials_file: File.expand_path("./private-key.json", ios_directory),
      groups: "ZOL",
      ipa_path: "#{ios_output_dir}/#{ios_app_scheme}.ipa"
      )
  end

  lane :deploy_version_rc do

    increment_build_number(
      build_number: ENV["TIMESTAMP"] # set a specific number
    )

    increment_version_number(
      version_number: ENV["GIT_TAG"]
    )

    build_adhoc

    release = firebase_app_distribution(
      app: ios_firebase_app_id,
      service_credentials_file: File.expand_path("./private-key.json", ios_directory),
      groups: "ZOL, clients",
      ipa_path: "#{ios_output_dir}/#{ios_app_scheme}.ipa"
      )
  end

  lane :deploy_version_release do

    increment_build_number(
      build_number: ENV["TIMESTAMP"] # set a specific number
    )

    increment_version_number(
      version_number: ENV["GIT_TAG"]
    )

    build_appstore

    upload_to_testflight(
      skip_submission: true,
      ipa: "#{ios_output_dir}/#{ios_app_scheme}.ipa",
      app_version: ENV["GIT_TAG"],
      build_number: ENV["TIMESTAMP"],
      skip_waiting_for_build_processing: true,

      ) # to only upload the build


  end

end