import { NOTIFICATION_TYPES } from '@/utils/notifications/notificationTypes';

const TEAM_ICON_TYPES = new Set([
  NOTIFICATION_TYPES.ADD_TO_TEAM,
  NOTIFICATION_TYPES.LEAGUE_SQUAD_INVITATION,
  NOTIFICATION_TYPES.LEAGUE_SQUAD_JOIN_REQUEST,
  NOTIFICATION_TYPES.LEAGUE_SQUAD_JOIN_REQUEST_STATUS,
  NOTIFICATION_TYPES.NEW_TEAM,
  NOTIFICATION_TYPES.RSVP_ALERT,
  NOTIFICATION_TYPES.TEAM_EXTERNAL_SOURCE_UPDATED,
  NOTIFICATION_TYPES.TEAM_MEMBERSHIP_REQUEST,
  NOTIFICATION_TYPES.TEAM_REQUEST,
  NOTIFICATION_TYPES.TOURNAMENT_CAPTAIN_TRANSFER,
  NOTIFICATION_TYPES.TOURNAMENT_TEAM_INVITATION,
  NOTIFICATION_TYPES.TOURNAMENT_TEAM_INVITATION_STATUS,
  NOTIFICATION_TYPES.TOURNAMENT_TEAM_JOIN_REQUEST,
  NOTIFICATION_TYPES.TOURNAMENT_TEAM_JOIN_REQUEST_STATUS,
  NOTIFICATION_TYPES.TOURNAMENT_TEAM_ROSTER_WARNING,
  NOTIFICATION_TYPES.TOURNAMENT_TEAM_STATUS,
]);

const CLUB_ICON_TYPES = new Set([
  NOTIFICATION_TYPES.AFFILIATION_HELP_REQUEST,
  NOTIFICATION_TYPES.AFFILIATION_HELP_STATUS,
  NOTIFICATION_TYPES.CLUB_MEMBERSHIP_REQUEST,
  NOTIFICATION_TYPES.CLUB_REQUEST,
]);

const EVENT_ICON_TYPES = new Set([
  NOTIFICATION_TYPES.COACH_REPORT_PUBLISHED,
  NOTIFICATION_TYPES.EVENT_ABSENCE_FINAL,
  NOTIFICATION_TYPES.EVENT_CANCELLATION,
  NOTIFICATION_TYPES.EVENT_CONVOCATION_PUBLISHED,
  NOTIFICATION_TYPES.EVENT_CREATED,
  NOTIFICATION_TYPES.EVENT_PARTICIPANT_REMINDER,
  NOTIFICATION_TYPES.EVENT_PUBLISHED,
  NOTIFICATION_TYPES.EVENT_REMINDER,
  NOTIFICATION_TYPES.EVENT_RSVP_STATUS_CHANGED,
  NOTIFICATION_TYPES.EVENT_TEAM_INVITED,
  NOTIFICATION_TYPES.EVENT_UPDATED,
  NOTIFICATION_TYPES.FEATURED_APPROVED,
  NOTIFICATION_TYPES.FEATURED_REJECTED,
  NOTIFICATION_TYPES.FEATURED_REQUEST,
  NOTIFICATION_TYPES.NEW_PARTICIPATION,
  NOTIFICATION_TYPES.OVERBOOKING_REQUEST,
  NOTIFICATION_TYPES.PARTICIPATION_REQUEST,
  NOTIFICATION_TYPES.RESERVATION_COMPLETE,
  NOTIFICATION_TYPES.RESERVATION_PLAYER_JOINED,
  NOTIFICATION_TYPES.RESERVATION_SOS_ALERT,
  NOTIFICATION_TYPES.TOURNAMENT_CLOSED,
]);

const LEAGUE_ICON_TYPES = new Set([
  NOTIFICATION_TYPES.LEAGUE_AUTOMATION,
  NOTIFICATION_TYPES.LEAGUE_COUNTER_PROPOSAL_RECEIVED,
  NOTIFICATION_TYPES.LEAGUE_MATCH_CANCELLED_NEGOTIATION_TIMEOUT,
  NOTIFICATION_TYPES.LEAGUE_MATCH_FINALIZED,
  NOTIFICATION_TYPES.LEAGUE_MATCH_FOUND,
  NOTIFICATION_TYPES.LEAGUE_MATCH_VALIDATED,
  NOTIFICATION_TYPES.LEAGUE_POST_SLOT_CANCELLED,
  NOTIFICATION_TYPES.LEAGUE_POST_SLOT_CHECK,
  NOTIFICATION_TYPES.LEAGUE_POST_SLOT_CONFIRMATION,
  NOTIFICATION_TYPES.LEAGUE_POST_SLOT_RESCHEDULED,
  NOTIFICATION_TYPES.LEAGUE_PROPOSAL_ACCEPTED,
  NOTIFICATION_TYPES.LEAGUE_PROPOSAL_DECLINED,
  NOTIFICATION_TYPES.LEAGUE_PROPOSAL_RECEIVED,
  NOTIFICATION_TYPES.LEAGUE_QUORUM_REACHED,
  NOTIFICATION_TYPES.LEAGUE_QUORUM_REMINDER,
  NOTIFICATION_TYPES.LEAGUE_SCORE_ADMIN_ESCALATED,
  NOTIFICATION_TYPES.LEAGUE_SCORE_DEADLINE_WARNING,
  NOTIFICATION_TYPES.LEAGUE_SCORE_DISPUTED_BY_OPPONENT,
  NOTIFICATION_TYPES.LEAGUE_SCORE_DUE,
  NOTIFICATION_TYPES.LEAGUE_SCORE_END_DUE,
  NOTIFICATION_TYPES.LEAGUE_SCORE_REMINDER_2H,
  NOTIFICATION_TYPES.LEAGUE_SCORE_START_INFO,
  NOTIFICATION_TYPES.LEAGUE_SCORE_SUBMITTED_BY_OPPONENT,
  NOTIFICATION_TYPES.LEAGUE_SCORE_VALIDATION_REQUIRED,
  NOTIFICATION_TYPES.LEAGUE_SEARCH_RELAUNCH_PROMPT,
  NOTIFICATION_TYPES.LEAGUE_SEARCH_STARTED,
  NOTIFICATION_TYPES.LEAGUE_SEARCH_STILL_RUNNING,
  NOTIFICATION_TYPES.LEAGUE_VENUE_BOOKED,
  NOTIFICATION_TYPES.MATCH_FOUND,
  NOTIFICATION_TYPES.REMATCH_REQUEST,
]);

const CHAT_ICON_TYPES = new Set([
  NOTIFICATION_TYPES.LEAGUE_MATCH_DISPUTED,
  NOTIFICATION_TYPES.NEW_LEAGUE_MATCH_MESSAGE,
  NOTIFICATION_TYPES.NEW_TEAM_MESSAGE,
  NOTIFICATION_TYPES.NEW_TEAM_PLAYER_MESSAGE,
  NOTIFICATION_TYPES.NEW_WHISPER,
]);

const LICENSE_ICON_TYPES = new Set([
  NOTIFICATION_TYPES.LICENSE_INSTALLMENT_OVERDUE,
  NOTIFICATION_TYPES.LICENSE_PAYMENT_CONFIRMED,
  NOTIFICATION_TYPES.LICENSE_PAYMENT_DUE,
  NOTIFICATION_TYPES.LICENSE_PAYMENT_REJECTED,
  NOTIFICATION_TYPES.LICENSE_PAYMENT_REMINDER,
]);

/**
 * @param {string | undefined | null} type
 * @returns {string}
 */
export const getNotificationIcon = (type) => {
  if (TEAM_ICON_TYPES.has(type)) return '\u{1F465}';
  if (CLUB_ICON_TYPES.has(type)) return '\u{1F3DB}\u{FE0F}';
  if (EVENT_ICON_TYPES.has(type)) return '\u{1F4C5}';
  if (LEAGUE_ICON_TYPES.has(type)) return '\u{26BD}';
  if (CHAT_ICON_TYPES.has(type)) return '\u{1F4AC}';
  if (LICENSE_ICON_TYPES.has(type)) return '\u{1F4B3}';
  if (type === NOTIFICATION_TYPES.SEARCH_ALERT_MATCH) return '\u{1F50E}';
  return '\u{1F514}';
};

/**
 * @param {string | Date | number | undefined | null} dateInput
 * @returns {string}
 */
export const formatNotificationRelativeTime = (dateInput) => {
  if (!dateInput) return '';
  const date = new Date(dateInput);
  if (Number.isNaN(date.getTime())) return '';

  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMs / 3600000);
  const diffDays = Math.floor(diffMs / 86400000);

  if (diffMins < 1) return "A l'instant";
  if (diffMins < 60) return `Il y a ${diffMins} min`;
  if (diffHours < 24) return `Il y a ${diffHours} h`;
  if (diffDays < 7) return `Il y a ${diffDays} j`;

  return date.toLocaleDateString('fr-FR', {
    day: '2-digit',
    month: 'short',
  });
};

export const NOTIFICATION_EMPTY_STATE_TITLE = 'Aucune notification';
export const NOTIFICATION_EMPTY_STATE_BODY = 'Les nouvelles notifications apparaitront ici.';
