import { NOTIFICATION_TYPES } from '@/utils/notifications/notificationTypes';

const TEAM_ICON_TYPES = new Set([
  NOTIFICATION_TYPES.ADD_TO_TEAM,
  NOTIFICATION_TYPES.LEAGUE_SQUAD_JOIN_REQUEST,
  NOTIFICATION_TYPES.NEW_TEAM,
  NOTIFICATION_TYPES.RSVP_ALERT,
  NOTIFICATION_TYPES.TEAM_MEMBERSHIP_REQUEST,
  NOTIFICATION_TYPES.TEAM_REQUEST,
]);

const CLUB_ICON_TYPES = new Set([
  NOTIFICATION_TYPES.AFFILIATION_HELP_REQUEST,
  NOTIFICATION_TYPES.AFFILIATION_HELP_STATUS,
  NOTIFICATION_TYPES.CLUB_MEMBERSHIP_REQUEST,
  NOTIFICATION_TYPES.CLUB_REQUEST,
]);

const EVENT_ICON_TYPES = new Set([
  NOTIFICATION_TYPES.EVENT_CANCELLATION,
  NOTIFICATION_TYPES.EVENT_REMINDER,
  NOTIFICATION_TYPES.FEATURED_APPROVED,
  NOTIFICATION_TYPES.FEATURED_REJECTED,
  NOTIFICATION_TYPES.FEATURED_REQUEST,
  NOTIFICATION_TYPES.NEW_PARTICIPATION,
  NOTIFICATION_TYPES.OVERBOOKING_REQUEST,
  NOTIFICATION_TYPES.PARTICIPATION_REQUEST,
  NOTIFICATION_TYPES.RESERVATION_COMPLETE,
  NOTIFICATION_TYPES.RESERVATION_PLAYER_JOINED,
  NOTIFICATION_TYPES.RESERVATION_SOS_ALERT,
]);

const LEAGUE_ICON_TYPES = new Set([
  NOTIFICATION_TYPES.LEAGUE_AUTOMATION,
  NOTIFICATION_TYPES.LEAGUE_MATCH_FINALIZED,
  NOTIFICATION_TYPES.LEAGUE_MATCH_FOUND,
  NOTIFICATION_TYPES.LEAGUE_MATCH_VALIDATED,
  NOTIFICATION_TYPES.LEAGUE_PROPOSAL_ACCEPTED,
  NOTIFICATION_TYPES.LEAGUE_SCORE_ADMIN_ESCALATED,
  NOTIFICATION_TYPES.LEAGUE_SCORE_DEADLINE_WARNING,
  NOTIFICATION_TYPES.LEAGUE_SCORE_DISPUTED_BY_OPPONENT,
  NOTIFICATION_TYPES.LEAGUE_SCORE_DUE,
  NOTIFICATION_TYPES.LEAGUE_SCORE_END_DUE,
  NOTIFICATION_TYPES.LEAGUE_SCORE_REMINDER_2H,
  NOTIFICATION_TYPES.LEAGUE_SCORE_START_INFO,
  NOTIFICATION_TYPES.LEAGUE_SCORE_SUBMITTED_BY_OPPONENT,
  NOTIFICATION_TYPES.LEAGUE_SEARCH_RELAUNCH_PROMPT,
  NOTIFICATION_TYPES.LEAGUE_VENUE_BOOKED,
  NOTIFICATION_TYPES.MATCH_FOUND,
  NOTIFICATION_TYPES.REMATCH_REQUEST,
]);

const CHAT_ICON_TYPES = new Set([
  NOTIFICATION_TYPES.LEAGUE_MATCH_DISPUTED,
  NOTIFICATION_TYPES.LEAGUE_PROPOSAL_RECEIVED,
  NOTIFICATION_TYPES.NEW_LEAGUE_MATCH_MESSAGE,
  NOTIFICATION_TYPES.NEW_TEAM_MESSAGE,
  NOTIFICATION_TYPES.NEW_TEAM_PLAYER_MESSAGE,
  NOTIFICATION_TYPES.NEW_WHISPER,
]);

/**
 * @param {string | undefined | null} type
 * @returns {string}
 */
export const getNotificationIcon = (type) => {
  if (TEAM_ICON_TYPES.has(type)) return '\u{1F465}';
  if (CLUB_ICON_TYPES.has(type)) return '\u{1F3DB}\u{FE0F}';
  if (EVENT_ICON_TYPES.has(type)) return '\u{1F4C5}';
  if (LEAGUE_ICON_TYPES.has(type)) return '\u{26BD}';
  if (CHAT_ICON_TYPES.has(type)) return '\u{1F4AC}';
  if (type === NOTIFICATION_TYPES.SEARCH_ALERT_MATCH) return '\u{1F50E}';
  return '\u{1F514}';
};
