import { NOTIFICATION_TYPES } from '@/domains/auth/authUseCases';

export const getNotificationIcon = (type) => {
  switch (type) {
    case NOTIFICATION_TYPES.NEW_WHISPER:
    case NOTIFICATION_TYPES.NEW_TEAM_MESSAGE:
    case NOTIFICATION_TYPES.NEW_TEAM_PLAYER_MESSAGE:
    case NOTIFICATION_TYPES.LEAGUE_PROPOSAL_RECEIVED:
    case NOTIFICATION_TYPES.LEAGUE_MATCH_DISPUTED:
      return '💬';

    case NOTIFICATION_TYPES.ADD_TO_TEAM:
    case NOTIFICATION_TYPES.NEW_TEAM:
    case NOTIFICATION_TYPES.TEAM_MEMBERSHIP_REQUEST:
    case NOTIFICATION_TYPES.TEAM_REQUEST:
    case NOTIFICATION_TYPES.RSVP_ALERT:
      return '👥';

    case NOTIFICATION_TYPES.CLUB_MEMBERSHIP_REQUEST:
    case NOTIFICATION_TYPES.CLUB_REQUEST:
      return '🏛️';

    case NOTIFICATION_TYPES.EVENT_REMINDER:
    case NOTIFICATION_TYPES.EVENT_CANCELLATION:
    case NOTIFICATION_TYPES.NEW_PARTICIPATION:
    case NOTIFICATION_TYPES.PARTICIPATION_REQUEST:
    case NOTIFICATION_TYPES.FEATURED_REQUEST:
    case NOTIFICATION_TYPES.FEATURED_APPROVED:
    case NOTIFICATION_TYPES.FEATURED_REJECTED:
    case NOTIFICATION_TYPES.OVERBOOKING_REQUEST:
    case NOTIFICATION_TYPES.RESERVATION_PLAYER_JOINED:
    case NOTIFICATION_TYPES.RESERVATION_SOS_ALERT:
    case NOTIFICATION_TYPES.RESERVATION_COMPLETE:
      return '📅';

    case NOTIFICATION_TYPES.SEARCH_ALERT_MATCH:
      return '🔎';

    case NOTIFICATION_TYPES.LEAGUE_MATCH_FOUND:
    case NOTIFICATION_TYPES.MATCH_FOUND:
    case NOTIFICATION_TYPES.LEAGUE_PROPOSAL_ACCEPTED:
    case NOTIFICATION_TYPES.LEAGUE_VENUE_BOOKED:
    case NOTIFICATION_TYPES.LEAGUE_SCORE_DUE:
    case NOTIFICATION_TYPES.LEAGUE_MATCH_VALIDATED:
    case NOTIFICATION_TYPES.LEAGUE_SEARCH_RELAUNCH_PROMPT:
    case NOTIFICATION_TYPES.LEAGUE_AUTOMATION:
    case NOTIFICATION_TYPES.REMATCH_REQUEST:
      return '⚽';

    default:
      return '🔔';
  }
};

