export const RouteNames = /** @type {const} */ ({
  AddCoach: 'AddCoach',
  AddSponsor: 'AddSponsor',
  AdminDashboard: 'AdminDashboard',
  AdminEvents: 'AdminEvents',
  AdminReports: 'AdminReports',
  AdminRevenue: 'AdminRevenue',
  AdminClaimList: 'AdminClaimList',
  AdminClaimDetail: 'AdminClaimDetail',
  AdminUserList: 'AdminUserList',
  AdminUserDetail: 'AdminUserDetail',
  AdminClubList: 'AdminClubList',
  AdminClubDetail: 'AdminClubDetail',
  AdminLeagueDisputes: 'AdminLeagueDisputes',
  AuthStackAccount: 'AuthStackAccount',
  AuthStackMessaging: 'AuthStackMessaging',
  AuthStackPlanning: 'AuthStackPlanning',
  Chat: 'Chat',
  Club: 'Club',
  ClubEdit: 'ClubEditPage',
  ClubFilters: 'ClubFilters',
  ClubList: 'ClubList',
  ClubMembershipRequests: 'ClubMembershipRequests',
  AssignCoachTeams: 'AssignCoachTeams',
  Conversation: 'Conversation',
  CreateClub: 'CreateClub',
  CreateSquad: 'CreateSquad',
  EventDetails: 'EventDetails',
  EventEdit: 'EventEdit',
  EventFilters: 'EventFilters',
  FacilityForm: 'FacilityForm',
  FacilityList: 'FacilityList',
  FeaturedRequestsList: 'FeaturedRequestsList',
  HomeTab: 'HomeTab',
  Login: 'Login',
  MercatoFilters: 'MercatoFilters',
  MyEventList: 'MyEventList',
  MyTeamList: 'MyTeamList',
  NotificationList: 'NotificationList',
  Profile: 'Profile',
  ProfileEdit: 'ProfileEdit',
  Register: 'Register',
  ReservationDetails: 'ReservationDetails',
  ReservationEdit: 'ReservationEdit',
  ReservationFilters: 'ReservationFilters',
  MissingPlayersView: 'MissingPlayersView',
  BookingCalendar: 'BookingCalendar',
  MyClubs: 'MyClubs',
  CMPlanning: 'CMPlanning',
  HighlightRequestsInbox: 'HighlightRequestsInbox',
  CreateSection: 'CreateSection',
  MultisportClubDetails: 'MultisportClubDetails',
  MultisportClubEdit: 'MultisportClubEdit',
  FeaturedRequests: 'FeaturedRequests',
  CMDashboard: 'CMDashboard',
  CMMembers: 'CMMembers',
  CMTeams: 'CMTeams',
  RequestsDashboard: 'RequestsDashboard',
  Search: 'Search',
  SearchEvents: 'SearchEvents',
  SearchClubs: 'SearchClubs',
  SearchReservations: 'SearchReservations',
  SearchRecruitment: 'SearchRecruitment',
  SearchHub: 'SearchHub',
  SearchAlerts: 'SearchAlerts',
  Team: 'Team',
  TeamDetails: 'TeamDetails',
  SquadDetails: 'SquadDetails', // New route for League Squad Details
  SquadEdit: 'SquadEdit',
  TeamEdit: 'TeamEdit',
  TeamFilters: 'TeamFilters',
  TeamList: 'TeamList',
  TeamMembershipRequests: 'TeamMembershipRequests',
  TeamStats: 'TeamStats',
  UserAvatar: 'UserAvatar',
  UserAddress: 'UserAddress',
  UserBirthdate: 'UserBirthdate',
  UserAffiliationGuide: 'UserAffiliationGuide',
  UserClubSearch: 'UserClubSearch',
  UserCategory: 'UserCategory',
  UserDetails: 'UserDetails',
  UserLevel: 'UserLevel',
  UserName: 'UserName',
  UserPhysique: 'UserPhysique',
  UserPosition: 'UserPosition',
  UserRole: 'UserRole',
  UserSection: 'UserSection',
  UserSport: 'UserSport',
  UserSportHistory: 'UserSportHistory',
  Welcome: 'Welcome',
  // Stacks
  EventStack: 'EventStack',
  ClubStack: 'ClubStack',
  TeamStack: 'TeamStack',
  AdminStack: 'AdminStack',
  ProfileStack: 'ProfileStack',
  
  // Event Wizard
  EventWizardType: 'EventWizardType',
  EventWizardTeam: 'EventWizardTeam',
  EventWizardInvites: 'EventWizardInvites',
  EventWizardLogistics: 'EventWizardLogistics',
  EventWizardParticipants: 'EventWizardParticipants',
  EventWizardValidationMode: 'EventWizardValidationMode',
  EventWizardDescription: 'EventWizardDescription',
  EventWizardVisibility: 'EventWizardVisibility',
  EventWizardLocation: 'EventWizardLocation',
  EventWizardRecap: 'EventWizardRecap',
  
  // History Wizard
  HistoryWizardStack: 'HistoryWizardStack',
  HistoryWizardClub: 'HistoryWizardClub',
  HistoryWizardCategory: 'HistoryWizardCategory',
  HistoryWizardLevel: 'HistoryWizardLevel',
  HistoryWizardPeriod: 'HistoryWizardPeriod',
  HistoryWizardRecap: 'HistoryWizardRecap',
  
  // Tactical
  TacticalBoard: 'TacticalBoard',
  TacticalSelectionV2: 'TacticalSelectionV2',
  TacticalBoardV2: 'TacticalBoardV2',
  
  // Recruitment Wizard
  AdWizardTeam: 'AdWizardTeam',
  AdWizardInfo: 'AdWizardInfo',
  AdWizardPositions: 'AdWizardPositions',
  AdWizardValidation: 'AdWizardValidation',
  AdWizardDescription: 'AdWizardDescription',
  AdWizardRecap: 'AdWizardRecap',
  AdWizardStack: 'AdWizardStack',
  RecruitmentAdDetails: 'RecruitmentAdDetails',
  RecruitmentAdEdit: 'RecruitmentAdEdit',
  
  // League Tabs (Gold Mode)
  LeagueHomeTab: 'LeagueHomeTab',
  LeagueDashboard: 'LeagueDashboard', // Dedicated screen name
  LeagueSquadTab: 'LeagueSquadTab',
  LeagueMatchTab: 'LeagueMatchTab',
  LeagueStandingsTab: 'LeagueStandingsTab',
  LeagueStack: 'LeagueStack', // Container for Wizard etc.
  LeagueRanking: 'LeagueRanking', // Ranking Screen
  LeagueMatchDetails: 'LeagueMatchDetails', // Standalone match details
  MatchDetails: 'MatchDetails',
  PastMatchDetails: 'PastMatchDetails', // Completed match details with ELO delta
  SquadSearch: 'SquadSearch',
  SquadFilters: 'SquadFilters',
  SquadRequests: 'SquadRequests',
});
