export const RouteNames = /** @type {const} */ ({
  AddCoach: 'AddCoach',
  AddSponsor: 'AddSponsor',
  Club: 'Club',
  ClubFilters: 'ClubFilters',
  ClubList: 'ClubList',
  CreateClub: 'CreateClub',
  Home: 'Home',
  Login: 'Login',
  Profile: 'Profile',
  ProfileEdit: 'ProfileEdit',
  Register: 'Register',
  UserAvatar: 'UserAvatar',
  UserBirthdate: 'UserBirthdate',
  UserName: 'UserName',
  UserRole: 'UserRole',
  UserSection: 'UserSection',
  Welcome: 'Welcome',
});
