export const RouteNames = /** @type {const} */ ({
  AddCoach: 'AddCoach',
  AddSponsor: 'AddSponsor',
  Chat: 'Chat',
  Club: 'Club',
  ClubFilters: 'ClubFilters',
  ClubList: 'ClubList',
  ClubMembershipRequests: 'ClubMembershipRequests',
  CreateClub: 'CreateClub',
  HomeTab: 'HomeTab',
  Login: 'Login',
  Profile: 'Profile',
  ProfileEdit: 'ProfileEdit',
  Register: 'Register',
  Search: 'Search',
  Team: 'Team',
  TeamDetails: 'TeamDetails',
  TeamEdit: 'TeamEdit',
  TeamFilters: 'TeamFilters',
  TeamList: 'TeamList',
  UserAvatar: 'UserAvatar',
  UserBirthdate: 'UserBirthdate',
  UserName: 'UserName',
  UserRole: 'UserRole',
  UserSection: 'UserSection',
  Welcome: 'Welcome',
});
